カムズの追加
bcdice/BCDice pull request #282
Opened 2020-11-05 15:31 UTC by raa0121

https://www.karikariume.com/comes 同人TRPGシステムですが、作者から作成依頼があり、作りました。

2020-11-05 15:34 UTC, ysakasin requested changes
寄稿ありがとうございます。

日本語以外の実装予定はないと思いますので、i18n機能は使わずに、従来通りRubyのソースコードにハードコードしてください。

2020-11-05 16:34 UTC, ysakasin requested changes

2020-11-05 16:34 UTC, ysakasin commented on lib/bcdice/game_system/Comes.rb
> +        @enabled_d66 = true
`@enabled_d66` は初期値が `true` なので、この記述は不要です

2020-11-08 11:21 UTC, raa0121 commented on lib/bcdice/game_system/Comes.rb
> +        @enabled_d66 = true
7907630  で直しました。

2020-11-08 11:27 UTC, ysakasin approved these changes

2020-11-08 11:27 UTC, merged

2020-11-08 11:27 UTC, ysakasin commented
@raa0121 寄稿ありがとうございます！　マージしました