ガラコと破戒の塔ダイスボット改良
bcdice/BCDice pull request #308
Opened 2020-11-24 15:18 UTC by GenKuzumochi

## GRコマンドを拡充
- 目標値のないダイスロール
- 柔軟なModifier
- 不安定（バッドステータス）による自動失敗に対応

## ダメージチャートを拡充
- `CDC1+1` などの算術演算
- `CDC0`で「ダメージを受けない」と表示するように修正（以前は1ダメージを参照するようになっていたが、誤りと思われる）
- xDTでダメージチャートVer2に対応
  - 公式サポートの無料PDF → http://deadlineheroes.sakura.ne.jp/pdf/garaco/damagechart_02.pdf ）
  - Ver2は選択ルールのため、xDCは残す

## GHAコマンドを追加
- ダメージ算出+HITコマンド

2020-11-30 12:52 UTC, ysakasin requested changes
PRありがとうございます！　下記、修正お願いします。

2020-11-30 12:52 UTC, ysakasin commented on lib/bcdice/game_system/Garako.rb
> +        cmd = parser.parse(command.sub(/^GR/i, "GR+0")) # GR5のようにコマンドと数値の間に記号を不要にするハック
このハックは今後の開発に影響が出そうなので行わないでください。正規表現を用いた方法に修正をお願いします。

2020-11-30 12:52 UTC, ysakasin commented on lib/bcdice/game_system/Garako.rb
> +        modifier = ArithmeticEvaluator.eval(Regexp.last_match(1))
```suggestion
        modifier = ArithmeticEvaluator.eval(m[1])
```

2020-11-30 12:52 UTC, ysakasin commented on lib/bcdice/game_system/Garako.rb
> +          damage = ArithmeticEvaluator.eval(Regexp.last_match(2)).to_i.clamp(0, 10)
- `DAMAGE_CHARTS` と `DAMAGE_CHARTS_V2` は分けずに一つの定数にしたほうが処理が簡潔にかけるかと思います。
- `ArithmeticEvaluator#eval` の結果は必ず整数になります。
- `Regexp.last_match` は使わずに、`Regexp#match` の結果を用いてください。

2020-11-30 12:52 UTC, ysakasin commented on lib/bcdice/game_system/Garako.rb
> +        ・判定 GRn#f （n：判定値、#f：不安定による自動失敗基準値）
この記述だと目標値を指定できないように読めるので、元のヘルプメッセージと同じように、目標値が記述できることを記載してください。

2020-12-02 07:33 UTC, GenKuzumochi commented on lib/bcdice/game_system/Garako.rb
> +        cmd = parser.parse(command.sub(/^GR/i, "GR+0")) # GR5のようにコマンドと数値の間に記号を不要にするハック
再検討の結果、GR+nをGRnにする必然性がなかったので、将来の拡張を阻害しないように今回はGRnの記法を廃止します。

2020-12-02 07:33 UTC, GenKuzumochi commented on lib/bcdice/game_system/Garako.rb
> +          damage = ArithmeticEvaluator.eval(Regexp.last_match(2)).to_i.clamp(0, 10)
確かに、DAMAGE_CHARTSにまとめられました！ifごと消せてスッキリしました

2020-12-11 12:44 UTC, merged

2020-12-11 12:47 UTC, ysakasin commented
コマンドの改善ありがとうございます。マージしました