サイコロ・フィクション特技テーブル処理を共通化
bcdice/BCDice pull request #309
Opened 2020-11-25 06:48 UTC by GenKuzumochi

- `RTT` ランダム指定特技
- `RTT[1-6]` XX分野ランダム指定特技
- `RCT` ランダム分野
- コマンド追加可能(`RTT`や`RTTn`相当の機能を別コマンドで実装済みのシステムがあるため)
- SaciFicSkillTableのコンストラクタでi18n等の差し込みが可能
- `《特技/分野n》`の形で出力

Draftなのでテストは未修正
方針確認が取れれば、サイコロ・フィクションをすべてこの実装で差し替えたいです。

## 表記について
実装の都合でかなり揺れがあります。
公式では`《特技》`か、`《特技/分野n》`(n=分野番号)の表記が多いようです。
BCDiceでもすべて`《特技/分野n》` に統一してもいいのではないかと思ってます。(公式のヤンヨグ、ピーカーブ、艦これRPG、インセインのシナリオ集等はこの表記）

`『分野』特技` シノビガミ
`「分野」≪特技≫` マギカロギア、インセイン
`「分野」《特技》` キルデス
`分野《特技》` 既存のSciFicSkillTable

スラッシュを全角にするか半角にするかは議論の余地あり

2020-11-30 13:08 UTC, ysakasin commented
@GenKuzumochi 
`SaiFicSkillTable#roll_command` にコマンド文字列を渡して分岐するというのは良いアイディアに思えます。
下記の指摘事項を加味した上で、テストが通るように書き進めてもらえませんか。

- `SaiFicSkill` に出目情報などを渡すのにテーブル全体を渡さないといけないのは冗長
  - するなら、分野の情報を丸々渡して、ダイスロールできるようにする
    - `SaiFicSkillTable::Category#roll`
  - するなら、クラス構造は `SaiFicSkillTable` の配下に移動したほうが良い。
- 表記は最も遊ばれているシノビガミでもルールブックと同じ表記ができるように、固定ではなく可変にするべきです
- privateなメソッドが多いと思うので、それは明示してください

2020-11-30 15:03 UTC, GenKuzumochi commented
> * するなら、分野の情報を丸々渡して、ダイスロールできるようにする
>    * SaiFicSkillTable::Category#roll
> * するなら、クラス構造は SaiFicSkillTable の配下に移動したほうが良い。

どちらかってことですかね？SaiFicSkillTable::Categoryのイメージがあんまりついていませんが、SaiFicSkillTableもSaiFicSkillもそんなに長くないので、複雑になるだけに感じます。
`SaiFicSkill`を`SaiFicSkillTable::SaiFicSkill`するだけならそちらを採用したいですが、あってますかね？

> 表記は最も遊ばれているシノビガミでもルールブックと同じ表記ができるように、固定ではなく可変にするべきです

シノビガミ等のルールブックでは紙面の都合か`《特技名》` となっています。
↓は現在のBCDiceの表記で、ルルブに`『分野』特技`といった表記は無いと思います。

`『分野』特技` シノビガミ
`「分野」≪特技≫` マギカロギア、インセイン
`「分野」《特技》` キルデス
`分野《特技》` 既存のSciFicSkillTable

2020-11-30 16:04 UTC, ysakasin commented
@GenKuzumochi 
伝え方が中途半端だったので以下にまとめます


## `SaiFicSkillTable::Category` について

`SaiFicSkillTable::Category` は `SaiFicSkillTable::SaiFicSkill` の代替案となります。以下のようなものを想定していました。

```ruby
class SaiFicSkillTable::Category
  def initialize(name, skills)
    @name = name
    @skills = skills
  end

  def roll(randomizer)
    index = randomizer.roll_sum(2, 6)
    skill = skills[index - 2]

    "《#{skill}/#{name}#{index}》"
  end

  private

  attr_reader :name
end

sorcery = SaiFicSkillTable::Category.new("妖術", ["異形化", "召喚術", ...省略])
sorcery.roll(randomizer) #=> "妖術《異形化》"
```

このようにすると、`SaiFicSkillTable`のコンストラクタで`Category`を生成しておくと処理が簡潔になります。
RTTの場合には`Category`を選択→`Category#roll`し、
RT[1-6]の場合には指定の `Category#roll` を行えば良いことになります。


## 特技の表記について

デフォルトの表記をは `《#{特技}/#{分野}#{n}》`で良いと思います。しかし、シノビガミではこの表記に馴染みがないため別の表記を指定したいです。そこで、スキルのフォーマットを指定できる余地を残してください。

この設定にはBuilderパターンを活用すると良いかもしれません

```ruby
nomal = SaiFicSkillTable.new(省略)
nomal.roll_command(command, randomizer) #=> "ランダム特技表(1,2) ＞ 《異形化/妖術2》"

specified = SaiFicSkillTable.new(省略).skill_format("%<category>《%<skill>》")
specified.roll_command(command, randomizer) #=> "ランダム特技表(1,2) ＞ 妖術《異形化》"
```

2020-11-30 19:20 UTC, GenKuzumochi commented
ありがとうございます。イメージつかめました。ルルブやサプリに《特技/分野n》の記述が積極的に使われているシステムはそちらに変更し、それ以外は現状の出力に揃えようかと思います。

> SaiFicSkillTable::Category#roll

こちらだとマギカロギア等で必要となる４種類の出力を作るのが結構厄介そうな気が。

* ランダム特技決定表(1,2) ＞ 「星」≪大地≫
* 指定特技（星）(2) ＞ 大地
* 「星」≪大地≫
* 大地

今後別のシステム等でもこういった表記が必要になるかもしれないので、できれば柔軟にしておきたいです。（SciFicSkillは一応そういう思想で書いた）

```ruby
# こういうこともしやすいように
skill = RTT.roll_skill(@randomizer)
"#{skill.to_s}の判定に成功すると『#{skill.category}』のマナを獲得し、『#{skill.skill_name}の精霊』を～"
```

2020-12-01 04:42 UTC, ysakasin commented
おっしゃるように最終的にオブジェクトを返すようにすると諸々解決するかと思います。 `SaiFicSkillTable::Category#roll` が文字列を返していたのは一例です。

最終的に返されるオブジェクトは一つの特技を示すインスタンスになるはずなので、以下のような物が好ましいのではないかと思います。

```ruby
class SaiFicSkillTable::Skill
  DEFAULT_FORMAT = "《%<name>/%<category>%<index>》".freeze

  def initialize(name, category, index, format: DEFAULT_FORMAT)
    @name = name
    @category = category
    @index = index
    @format = format
  end

  def to_s
    format(@format, name: name, category: category, index: index)
  end

  attr_reader :name, :category, :index
end
```

蛇足：`"#{a.to_s}"`と`"#{a}"`は等価です。

2020-12-03 09:12 UTC, GenKuzumochi commented
レビュー受けて反映しました。テスト通すのは後ほどやります。
`SaiFicSkillTable::Category`、実質3行ぐらいなのであまり処理が完結になった気がしない:thinking:。

2020-12-03 10:22 UTC, ysakasin commented on lib/bcdice/dice_table/sai_fic_skill_table.rb
> +        end
```suggestion
        @categories = items.map.with_index(1) do |(name, skills), index|
          SaiFicSkillTable::Category.new(name, skills, index, s_format)
        end
```

2020-12-03 10:27 UTC, ysakasin commented on lib/bcdice/dice_table/sai_fic_skill_table.rb
> +          roll_skill(randomizer, index + 1).to_s(@rttn_format)
`roll_skill` を使うのではなく、 `category[index + 1].roll()` のようにするのが良いと思います。現状だと`roll_skill`に二つの役割を持ってしまっているので、`roll_skill`はRTT相当に注力するのが良さそうです。

2020-12-03 10:31 UTC, ysakasin commented on lib/bcdice/dice_table.rb
> +require "bcdice/dice_table/sai_fic_skill_table_category"
クラス `A::B::C` は `a/b/c.rb` に配置するというのがRubyの作法なので、そのように変更してください。

また、skillもcategoryもsai_fic_skill_tableと合わせて使う物なので、ここではなくsai_fic_skill_table.rbでロードするようにしてください。

2020-12-03 10:32 UTC, ysakasin commented on lib/bcdice/dice_table/sai_fic_skill_table.rb
> +        c = command.upcase
ダイスボットに入ってくる文字列は前処理によって全て大文字化されるため、ここでの `String#upcase` は不要となります。

2020-12-03 10:35 UTC, ysakasin commented on lib/bcdice/dice_table/sai_fic_skill_table.rb
> +          roll_skill(randomizer).to_s(@rtt_format)
```ruby
roll_category(randomizer).roll(randomizer).to_s
```
と書いてもよいかもしれません。多分好みによる

2020-12-03 10:48 UTC, ysakasin commented on lib/bcdice/dice_table/sai_fic_skill_table_skill.rb
> +            format(text_format, category_dice: category_dice, row_dice: row_dice, category_name: category_name, skill_name: skill_name, text: to_s)
`Skill#to_s` が入れ子になっているのが気になります。

`SaiFicTable` の結果全体をこいつで出力したいからこのようになっているのだと思いますが、結果全体のフォーマットとSkillのインスタンスのペアを持つようなクラスを作ってもいいかもれません。

2020-12-03 10:49 UTC, ysakasin requested changes
コード量は増えているかもしれませんが、処理が分割され各クラスの役割が減ったことで見通しがよくなったと思います。

いくつか気になった点と、Rubyの記法についてコメントしたので修正お願いします。

2020-12-03 16:19 UTC, GenKuzumochi commented on lib/bcdice/dice_table/sai_fic_skill_table.rb
> +          roll_skill(randomizer).to_s(@rtt_format)
こうすればroll_skill自体消せそうですね
RTT/RTTn以外でランダム特技したい場合にちょっと遠回りになりますが、見ればわかるぐらいのコード量ですし

2020-12-03 16:38 UTC, GenKuzumochi commented on lib/bcdice/dice_table/sai_fic_skill_table_skill.rb
> +            format(text_format, category_dice: category_dice, row_dice: row_dice, category_name: category_name, skill_name: skill_name, text: to_s)
自分でも気持ち悪いなぁと思ってましたが、再考するとそもそも引数なしのto_sだけあれば十分そうですね。RTT/RTTNの処理は`SciFicSkillTable#roll_command`でやればよく、ダイスボット側で必要なときもcategory_nameとかを直で使えば済む話で。

2020-12-07 09:28 UTC, GenKuzumochi commented
レビュー反映とテストが通るようにし、ブランチをDraft→Openに。
Discordで`《特技／分野n》`のスラッシュの全角半角を迷っていましたが、公式に従って全角としました。

現状SaiFicSkillTableを使ってないシステムにも続いて使うように書き換える予定ですが、別PRに切ったほうがrevertしやすそう

2020-12-07 11:12 UTC, ysakasin commented on lib/bcdice/dice_table/sai_fic_skill_table.rb
> +require "bcdice/dice_table/sai_fic_skill_table/skill.rb"
```suggestion
require "bcdice/dice_table/sai_fic_skill_table/category"
require "bcdice/dice_table/sai_fic_skill_table/skill"
```

2020-12-07 11:16 UTC, ysakasin requested changes
よくなったと思います！

あと、失念していましたが、以前のコメントにあった以下のようなことができなくなってしまうので、`#roll_skill` は残しておいたほうが良さそうです。

```
skill = RTT.roll_skill(@randomizer)
"#{skill}の判定に成功すると『#{skill.category}』のマナを獲得し、『#{skill.name}の精霊』を～"
```

2020-12-07 11:16 UTC, ysakasin commented on lib/bcdice/dice_table/sai_fic_skill_table/skill.rb
> +          @skill_name = skill_name
`skill.skill_name` のようになってしまうので、 単に `name` が良いと思います。

2020-12-07 11:48 UTC, ysakasin commented
> 現状SaiFicSkillTableを使ってないシステムにも続いて使うように書き換える予定ですが、別PRに切ったほうがrevertしやすそう

別PRで作業で良いと思います。マギカロギアはi18n化の作業もあるので、私の方でやります。

2020-12-09 06:54 UTC, GenKuzumochi commented
roll_skillついでに一部にYARD付与しました。
マギカロギア、ランダム特技を選ぶところをラムダ式で置いてあるので、便利ですが厄介…

2020-12-09 08:03 UTC, GenKuzumochi commented
あ～、少々マージお待ち下さい。
カードランカーにカテゴリと番号を指定してロール無しで特技を抜く処理があったので、SaiFicSkillTableにget_skillを足します。
（便利な状況があるかもしれないけど、RTT5,10みたいな共通コマンドを追加するほど需要は無いよなぁ）

2020-12-09 08:23 UTC, ysakasin commented
@GenKuzumochi 
> SaiFicSkillTableにget_skillを足します。

メソッドを追加するのではなく以下のようにアクセスできるようにすれば良いと思います

```ruby
table.categories[0].skills[0]
```

2020-12-09 13:51 UTC, ysakasin commented
表の名前の表示ですが、RTTが「Random Tokugi Table」の頭文字なので、「ランダム特技表」系に統一でいきましょう

2020-12-09 15:38 UTC, ysakasin approved these changes
良いと思います！　レビューに根気強く対応していただきありがとうございます！！

2020-12-09 15:38 UTC, merged

2020-12-09 15:52 UTC, GenKuzumochi commented
ありがとうございます！丁寧なレビュー助かりました！