Emokloreの追加
bcdice/BCDice pull request #310
Opened 2020-11-26 13:20 UTC by kokoa0429

Emokloreという新しいシステムを追加しました。
よろしくお願いします。

2020-11-26 13:34 UTC, ysakasin requested changes
寄稿ありがとうございます！　いくつかコメントしましたので、返答か修正お願いします！

2020-11-26 13:34 UTC, ysakasin commented on lib/bcdice/game_system/Emoklore.rb
> +      MESSAGETEXT
`DA` コマンドのヘルプを追記してください

2020-11-26 13:34 UTC, ysakasin commented on lib/bcdice/game_system/Emoklore.rb
> +        when /\d*DM( )*<=( )*\d/
空白にマッチするようにしている意図がわかりませんでした。消し忘れであれば削除を、意味がるようならばコメントで細くをお願いします。

2020-11-26 13:34 UTC, ysakasin commented on lib/bcdice/game_system/Emoklore.rb
> +        if (m = /(\d*)DM<=(\d+)/i.match(command))
以下のように、マッチしなかった場合に早期リターンするのがよくある書き方です。

```ruby
m = /正規表現/.match(command)
unless m
  return nil
end

# コマンドの処理 ....
```

2020-11-26 13:34 UTC, ysakasin commented on lib/bcdice/game_system/Emoklore.rb
> +        @fumble_value = 10
`@critical_value` も `@fumble_value` も変動しない値のようなので、定数にしてください

2020-11-26 13:34 UTC, ysakasin commented on lib/bcdice/game_system/Emoklore.rb
> +      end
stringが書き換わらない場合にはこのメソッドの定義は不要です

2020-11-26 13:34 UTC, ysakasin commented on lib/bcdice/game_system/Emoklore.rb
> +        values_success = values_tmp.select { |num| num <= success_threshold }
配列の中の該当する要素数の数え上げには `array.count { |x| x <= target }` のように書くとすっきりかけます。のちにダイス目を使わないような箇所は、これを使って書き換えてもらえると助かります。

2020-11-26 13:48 UTC, kokoa0429 commented on lib/bcdice/game_system/Emoklore.rb
> +      end
過去のコードが残ってしまっていました。削除しました。

2020-11-26 13:48 UTC, kokoa0429 commented on lib/bcdice/game_system/Emoklore.rb
> +        @fumble_value = 10
了解しました。

2020-11-26 13:50 UTC, kokoa0429 commented on lib/bcdice/game_system/Emoklore.rb
> +        values_success = values_tmp.select { |num| num <= success_threshold }
了解しました。

2020-11-26 13:52 UTC, kokoa0429 commented on lib/bcdice/game_system/Emoklore.rb
> +      MESSAGETEXT
了解しました。

2020-11-26 14:07 UTC, kokoa0429 commented on lib/bcdice/game_system/Emoklore.rb
> +        when /\d*DM( )*<=( )*\d/
削除しました。

2020-11-26 15:12 UTC, ysakasin commented
@kokoa0429 すみません「エモクロア」や「Emoklore」と検索してもTRPGシステムが何も出てこないのですが、同人もしくはj未発表のTRPGなのでしょうか

2020-11-27 06:05 UTC, kokoa0429 commented
@ysakasin はい。Emokloreは未発表のシステムです。今年中にはリリースされる予定です。BCDiceには先行してリクエストを飛ばさせていただきました。

2020-11-27 06:53 UTC, kokoa0429 commented on lib/bcdice/game_system/Emoklore.rb
> +        if (m = /(\d*)DM<=(\d+)/i.match(command))
勉強になります。。 修正しました

2020-12-01 11:00 UTC, kokoa0429 commented
@ysakasin 
時間がかかってしまって申し訳ないです。
レビューをお願いいたします。m(__)m

2020-12-01 12:09 UTC, ysakasin commented
@kokoa0429

修正ありがとうございます。
DAコマンドのヘルプメッセージの説明文中に `b` という変数が出てきますが、これは `a` の誤りでしょうか？

2020-12-02 12:06 UTC, kokoa0429 commented
@ysakasin 
bは変数ではなくbaseのbで `bDA3`という形の使い方を想定していました。 
説明文と実装を変更しました。

2020-12-07 12:09 UTC, ysakasin approved these changes

2020-12-07 12:09 UTC, merged

2020-12-07 12:09 UTC, ysakasin commented
@kokoa0429 寄稿ありがとうございます。マージしました。