SaiFicSkillTableのi18n対応とインセイン実装
bcdice/BCDice pull request #319
Opened 2020-12-10 11:35 UTC by GenKuzumochi

* `SaiFicSkillTable.from_i18n`を追加し、インセインをそれに基づいてSaiFicSkillTableに移行
  * 書式文字列はyamlから差し込み
  * コマンドエイリアス(TVT=RTT1)は日本語版に準拠
* インセインの公式シナリオ集等でも使用されている《特技／分野n》の表記法に差し替え（日本語版）

2020-12-10 12:20 UTC, ysakasin requested changes

2020-12-10 12:20 UTC, ysakasin commented on i18n/Insane/ko_kr.yml
> +      s_format: '「%<category_name>s」≪%<skill_name>s≫'
日本語版はデフォルト値が使われているので、これはBCDice全体の共通設定翻訳に移動させたいですね。 `i18n/ko_kr.yml` に移動して欲しいです。

そのうえで、特殊な表記の場合にここにもかけるように、機能自体は残しておいて欲しいです。

2020-12-10 12:20 UTC, ysakasin commented on i18n/Insane/ko_kr.yml
> +      s_format: '「%<category_name>s」≪%<skill_name>s≫'
加えて、翻訳が不明な場合のフォールバック先は英語ではなく日本語にするようにお願いします。BCDice全体としてそのようにする方針です。

2020-12-10 15:38 UTC, GenKuzumochi commented on i18n/Insane/ko_kr.yml
> +      s_format: '「%<category_name>s」≪%<skill_name>s≫'
`DiceTable::SaiFicSkillTable.from_i18n("RTT", locale)`としておいて、特殊な表記が必要な時は`DiceTable::SaiFicSkillTable.from_i18n("Insane.RTT", locale)`とする感じでしょうか？

2020-12-11 11:57 UTC, ysakasin commented on i18n/Insane/ko_kr.yml
> +      s_format: '「%<category_name>s」≪%<skill_name>s≫'
その挙動は意図と違います。

`DiceTable::SaiFicSkillTable.from_i18n("Insane.RTT", locale)` と入力し、rtt_formatを決定する場合に

1. `translate("Insane.RTT.rtt_format")` を参照する
2. `translate("rtt_format")` を参照する
3. 定数 `DEFAULT_RTT` を参照する

という流れで最初に参照できた物を採用する、というのを想定していました

2020-12-11 12:01 UTC, ysakasin commented on lib/bcdice/dice_table/sai_fic_skill_table.rb
> +        table = table.filter { |k, _v| [:rtt_format, :rttn_format, :rct_format, :s_format].include?(k) }
`Hash#filter` はRuby 2.5だとサポートされていないので、 `Hash#select` を用いてください

エラ〜ログ：https://github.com/bcdice/BCDice/pull/319/checks?check_run_id=1530284643#step:6:4

2020-12-15 16:10 UTC, GenKuzumochi commented on i18n/Insane/ko_kr.yml
> +      s_format: '「%<category_name>s」≪%<skill_name>s≫'
`from_i18n`の場合、2.3.4で十分なのでそちらを実装しました。

2020-12-15 16:29 UTC, ysakasin approved these changes
LGTM!

2020-12-15 16:29 UTC, merged