[WIP]サイコロ・フィクションでSaiFicSkillTableを使うように
bcdice/BCDice pull request #329
Opened 2020-12-19 11:43 UTC by GenKuzumochi

作業重複防止Draft
シノビガミとビギニングアイドルは変更点が多くなるので、もう少しかかります

- [ ] シノビガミ
- [ ] ビギニングアイドル
- [x] ハンターズ・ムーン
- [x] ブラッド・クルセイド
- [x] カードランカー
- [x] キルデスビジネス
- [x] ブラッドムーン
- [x] 艦これRPG
- [x] ストラトシャウト

2020-12-19 12:26 UTC, ysakasin commented
@GenKuzumochi ビギニングアイドルはコード全域に渡ってひどいことになっているので、いったん対応せずに無視してください。

2020-12-19 12:56 UTC, GenKuzumochi commented
表関連の作業が追いついてないだけかと思ったら、結構変えないといけないかんじですかね。ではシノビガミだけ後日修正します。

ちなみに、他のシステムに関しても出力の変更は控えました（ぶっちゃけテストを修正するも面倒なので）

2020-12-23 11:45 UTC, ysakasin requested changes

2020-12-23 11:45 UTC, ysakasin commented on lib/bcdice/game_system/CardRanker.rb
> +          return " ＞ スペシャル ＞ " + RTT.roll_command(@randomizer, "RM")
`SaiFicSkillTable#roll_skill`を使った方が良いと思います。

2020-12-25 06:26 UTC, GenKuzumochi commented on lib/bcdice/game_system/CardRanker.rb
> +          return " ＞ スペシャル ＞ " + RTT.roll_command(@randomizer, "RM")
「ランダムモンスター選択(x,y) ＞ 」の文を出す方法がRMで振るしかなさそうなんですよね。
独自で出力してもいいかなとも思いましたが、頑張るよりこのほうがDRYかなと

2020-12-25 06:32 UTC, ysakasin commented on lib/bcdice/game_system/CardRanker.rb
> +          return " ＞ スペシャル ＞ " + RTT.roll_command(@randomizer, "RM")
なるほど……

2020-12-25 06:32 UTC, ysakasin approved these changes

2020-12-25 06:32 UTC, merged

2020-12-25 06:32 UTC, ysakasin commented
@GenKuzumochi ありがとうございます！