『アルケミア・ストラグル』のダイスボット AlchemiaStruggle を追加
bcdice/BCDice pull request #341
Opened 2020-12-25 03:36 UTC by ViVi-shark

# ゲームについて

* http://www.shinkigensha.co.jp/book/978-4-7753-1891-1/

　Role&Roll のサポートがまだ存在しないのですが、上記の新紀元社のページにあるとおり、 2020/12/24 に発行されたタイトルです。

# コマンド一覧（コード内から転載）

```
        ■ ダイスロール（ XAS ）
          ＸＤをロールします。標準の XB6 と等価です。
          例） 5AS
        
        ■ ダイスロール＆最大になるようにピック（ XASY ）
          ＸＤをロールし、そこから最大になるようにＹ個をピックします。
          例） 4AS3

        ■ 表
          ・軌跡の触媒
            ・エレメント (CELE, CElement)
            ・アルケミア (CALC, CAlchemia)
            ・インフォーマント (CINF, CInformant)
            ・イノセンス (CINN, CInnocence)
            ・アクワイヤード (CACQ, CAcquired)
          ・携行品
            ・Ｓサイズ (ARS, ArticleS)
            ・Ｍサイズ (ARM, ArticleM)
            ・Ｌサイズ (ARL, ArticleL)
          ・ＰＣ情報獲得表 (PCI, PCInformation)
          ・理由表 (REA, Reason)
          ・交流表 (ASS, Associate)
          ・接触のきっかけ表 (CON, Contact)
```

# ダイスロール機能

　現時点ではそこまで意味のある（＝標準のコマンドと差異のある）機能ではありませんが、タイトル独自性の高い機能が追加されたときに、エンドユーザーにとってのコマンド体型が現在と一貫しなくなるようでは困ると考えて、独自ロールコマンドを用意してあります。

# 表

　よくある表です。
　「D66 の左側を偶奇しか見ない」表がいくつかあります。

2020-12-25 03:55 UTC, ViVi-shark commented
ちょっと不備を見つけたので

2020-12-25 03:57 UTC, ysakasin commented
@ViVi-shark 不備修正のコミットは同じブランチにpushし、このPRを再度オープンしてください

2020-12-25 04:00 UTC, ViVi-shark commented
@ysakasin 修正しました

2020-12-25 06:29 UTC, ysakasin requested changes
寄稿ありがとうございます！
気になる点を指摘しましたので、確認/修正お願いします。

2020-12-25 06:29 UTC, ysakasin commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +        c = resolve_alias command
`Base#eval_game_system_specific_command`の引数commandは大文字かされた状態で渡されます。エイリアス探索のロジックを書くのではなく、 `ALIAS[command] || command` のようにして対応できないでしょうか？

2020-12-25 06:29 UTC, ysakasin commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +      def self.make_d66_small_table(name, items)
ビルダメソッドを作るのではなく、`D66Table`を継承したクラスを作成し、そのコンストラクタで処理するのが良いかと思います。

```ruby
class SomeTable < D66Table
  def initialize(name, odd:, even:)
    # 省略
  end
end

SomeTable.new(
  "名前",
  odd: [],
  even: []
)
```

2020-12-25 06:29 UTC, ysakasin commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +      }.freeze
```suggestion
      }.transform_keys(&:upcase).freeze
```

2020-12-25 06:29 UTC, ysakasin commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +      }.freeze
```suggestion
      }.transform_keys(&:upcase).freeze
```

2020-12-25 06:29 UTC, ysakasin commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +      }.freeze
```suggestion
      }.transform_keys(&:upcase).freeze
```

2020-12-25 06:29 UTC, ysakasin commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +        CATALYST_TABLES.merge(ARTICLE_TABLES).merge(DRAMA_SEQUENCE_TABLES)
```suggestion
      TABLES =
        CATALYST_TABLES.merge(ARTICLE_TABLES).merge(DRAMA_SEQUENCE_TABLES)
```

2020-12-25 06:29 UTC, ysakasin commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +        ).freeze
```suggestion
      alias_catalyst_tables = CATALYST_TABLES.keys.map { |key| [key[0, 4], key]}
      alias_article_tables = ARTICLE_TABLES.map { |key| [key[0, 2] + key[-1], key]}
      alias_drama_sequence_tables = DRAMA_SEQUENCE_TABLES.map { |key| [key[0, 3], key]}
      ALIAS = alias_catalyst_tables.merge(alias_article_tables, alias_drama_sequence_tables).freeze
```

2020-12-25 06:29 UTC, ysakasin commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +        "(#{rolled_dice_list.size}D) ＞ #{make_dice_text(rolled_dice_list)}"
```suggestion
        "(#{rolled_dice_list.size}D6) ＞ #{make_dice_text(rolled_dice_list)}"
```

2020-12-25 06:29 UTC, ysakasin commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +        "(#{rolled_dice_list.size}D>>#{pick_dice_count}D) ＞ #{make_dice_text(rolled_dice_list)} >> #{make_dice_text(picked_dice_list)} ＞ #{picked_dice_list.sum}"
```suggestion
        "(#{rolled_dice_list.size}D6>>#{pick_dice_count}D6) ＞ #{make_dice_text(rolled_dice_list)} >> #{make_dice_text(picked_dice_list)} ＞ #{picked_dice_list.sum}"
```

2020-12-25 06:29 UTC, ysakasin commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +          例） 4AS3
```suggestion
        ■ ダイスロール（ xAS ）
          xDをロールします。
          例） 5AS
        
        ■ ダイスロール＆最大になるようにピック（ xASy ）
          xDをロールし、そこから最大になるようにy個をピックします。
          例） 4AS3
```

数字の入力場所とキーワードが区別しやすいようにしてください

2020-12-25 06:29 UTC, ysakasin commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +      end
```suggestion
      def try_roll_alchemia(command)
        match = ROLL_REG.match(command)
        return nil unless match

        roll_dice_count = match[1].to_i

        if match[2].nil?
          # ロールのみ（ピックなし）:

          result = roll_alchemia(roll_dice_count)
          return make_roll_text(result)
        else
          # ロールして最大値をピック:

          pick_dice_count = match[2].to_i

          result = roll_alchemia_and_pick(roll_dice_count, pick_dice_count)
          return make_roll_and_pick_text(result[:rolled_dices], pick_dice_count, result[:picked_dices])
        end
      end
```

対応外コマンドを弾く場合には、早期リターンが望ましいです

2020-12-25 06:29 UTC, ysakasin commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +          dice_list.sort[-pick_dice_count..-1]
```suggestion
          dice_list.sort.pop(pick_dice_count)
```

末尾から複数個の要素をとるのは `Array#pop` が便利です

2020-12-25 06:29 UTC, ysakasin commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +        "(#{rolled_dice_list.size}D>>#{pick_dice_count}D) ＞ #{make_dice_text(rolled_dice_list)} >> #{make_dice_text(picked_dice_list)} ＞ #{picked_dice_list.sum}"
あと、 `>>` は見慣れない表記なのですが、どういう意図なのでしょうか。

2020-12-25 07:57 UTC, ViVi-shark commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +        "(#{rolled_dice_list.size}D) ＞ #{make_dice_text(rolled_dice_list)}"
@ysakasin 

　ルールブック内において、面数を省略した「３Ｄ」「８Ｄ」などの表記になっている（※６面以外のダイスを使用しないルールである）ので、それに倣った記述にしてありました。

　面数を明記する形式が推奨されているのでしょうか？（もしそうなら、それにしたがいます）
　（[比較的最近のほかのダイスボットを見ても output の先頭が独自コマンド書式だったりする](https://github.com/bcdice/BCDice/blob/master/test/data/SteamPunkers.toml#L4)ので、推奨されている形式がよくわかりませんでした）

2020-12-25 08:14 UTC, ysakasin commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +        "(#{rolled_dice_list.size}D) ＞ #{make_dice_text(rolled_dice_list)}"
面数を明記する形式を推奨しています。通常の加算ダイスでも`3D`のようにコマンド実行ができますが、出力では`3D6`となります。

カッコに何を記述するかは確かにまばらなのですが、基準としている物は以下になります。
- コマンドとして実行できるものは無条件でOK
- コマンドで行われたダイスロールを把握しやすいか？

ルールブックは誌面の問題などがあり省略することも多いです。しかし、BCDiceは多様なゲームシステムに対応しており、`3D`がで何面ダイスが実行されるかはシステムにより揺らぎがあるので、出力では誤解が生まれないように正確に表記したいです。

2020-12-25 08:20 UTC, ysakasin commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +        "(#{rolled_dice_list.size}D>>#{pick_dice_count}D) ＞ #{make_dice_text(rolled_dice_list)} >> #{make_dice_text(picked_dice_list)} ＞ #{picked_dice_list.sum}"
あ、現在のBCDiceだとこの表記は `7D6KH4` とかけますね。

```
[DiceBot]> 7D6KH4
(7D6KH4) ＞ 16[2,2,2,4,4,4,4] ＞ 16
```

2020-12-25 08:29 UTC, ViVi-shark commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +        "(#{rolled_dice_list.size}D>>#{pick_dice_count}D) ＞ #{make_dice_text(rolled_dice_list)} >> #{make_dice_text(picked_dice_list)} ＞ #{picked_dice_list.sum}"
@ysakasin 

　ルールブック内での表記は、「４Ｄ⯈３Ｄ」（※ダイス数を示す２項の間に、頂角が右にある二等辺三角形）となっており、それに近いニュアンスを再現する意図です。

　以下は検討して没にした記号です。

* 「`⯈`」 は、環境やフォントによっては表示されない場合が想定される。
* 「`＞`」は、ダイスボット全般で別の意味をもって利用されている。
* 「 `>` 」は、不等号とまぎらわしい。（多くのゲームで閾値チェックなどに不等号を用いていることも考慮）
* 「 `=>` 」も、微妙に不等号 `>=` とまぎらわしい。
  * コードを読み書きするひとはファットアローと大なりイコールの区別を自然とできますが、一般的なエンドユーザーはそうでもないという認識です。（セッション中に不等号のつもりで `=>` と入力する事例を散見します） （実際に [`=>` を不等号あつかいで解釈するダイスボットあります](https://github.com/bcdice/BCDice/blob/master/test/data/OracleEngine.toml#L405)し……）
* 「 `->` 」は、ダイスロールのインライン解決で使われる表記であり（例：[デッドラインヒーローズ](https://github.com/bcdice/BCDice/blob/master/test/data/DeadlineHeroes.toml#L345)，[でたとこサーガ](https://github.com/bcdice/BCDice/blob/master/test/data/DetatokoSaga.toml#L67)）、それとはニュアンスが明確に異なる。
  *  なお、これはどどんとふにおけるユーザー追加のダイス表の出力に合わせた形式という認識です。なのでそろそろ気にしなくていいかもしれません。

---

　より優れた案があればそれに合わせます。

2020-12-25 08:36 UTC, ysakasin commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +        "(#{rolled_dice_list.size}D>>#{pick_dice_count}D) ＞ #{make_dice_text(rolled_dice_list)} >> #{make_dice_text(picked_dice_list)} ＞ #{picked_dice_list.sum}"
なるほど… 
`>>` はBCDiceだと不等号として扱われます。Saipageなどで試して欲しいのですが、`2D6>>7` はBCDice的には妥当なコマンドです。

元の表記を考えると、`>>` でも良いとは思います。
それでも一つ案をあげるとすると `|>` はいかがでしょうか。

2020-12-25 08:40 UTC, ysakasin commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +        "(#{rolled_dice_list.size}D>>#{pick_dice_count}D) ＞ #{make_dice_text(rolled_dice_list)} >> #{make_dice_text(picked_dice_list)} ＞ #{picked_dice_list.sum}"
BCDiceの比較演算子の判別方法は以下の通りです

https://github.com/bcdice/BCDice/blob/master/lib/bcdice/normalize.rb#L5-L24

2020-12-25 08:57 UTC, ViVi-shark commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +        "(#{rolled_dice_list.size}D>>#{pick_dice_count}D) ＞ #{make_dice_text(rolled_dice_list)} >> #{make_dice_text(picked_dice_list)} ＞ #{picked_dice_list.sum}"
　もろもろありがとうございます。理解しました。
　`>>` に本来の別の意味があるとなると、それをつかうのは好ましくないので、

> それでも一つ案をあげるとすると |> はいかがでしょうか。

　これに変更しました。 https://github.com/bcdice/BCDice/pull/341/commits/952e2638a032660ae76747346db9d402e19a2bd1 https://github.com/bcdice/BCDice/pull/341/commits/b059d64c9aa4b09043d9320a835666165bb8a2ca

2020-12-25 09:29 UTC, ViVi-shark commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +        "(#{rolled_dice_list.size}D) ＞ #{make_dice_text(rolled_dice_list)}"
　承知しました。

　明示しました。 https://github.com/bcdice/BCDice/pull/341/commits/f0fcaa819933b2d925cc6f1be2cdc3b921587f56 https://github.com/bcdice/BCDice/pull/341/commits/44324b93a70fbf9a383def9b5bc2b86695e8e8f8

2020-12-25 09:34 UTC, ViVi-shark commented on lib/bcdice/game_system/AlchemiaStruggle.rb
> +        ).freeze
https://github.com/bcdice/BCDice/pull/341/commits/26938127db632c73bc61ff24bc17b50a5d251f06, https://github.com/bcdice/BCDice/pull/341/commits/217d9a6cb8597446742733bf463ca86eae5d66db, https://github.com/bcdice/BCDice/pull/341/commits/1e36dffff56118cbc4dbbca097cbd1bdbeeab7a4, https://github.com/bcdice/BCDice/pull/341/commits/695740595cdb7d35a2cc516878f2876dd56a3884

---

* `map` の結果に `.to_h` しないと `Enumerable` のままなので `.merge` できない
* `Hash#merge` が複数の引数を取れるのは Ruby 2.6 以降（そして自動テストには 2.5 の想定がある）
  * https://docs.ruby-lang.org/ja/2.5.0/class/Hash.html#I_MERGE
  * https://docs.ruby-lang.org/ja/2.6.0/class/Hash.html#I_MERGE

　という問題があったのでそのままは採用していませんが、ほぼ同じ形にリファクタしました。

2020-12-26 03:53 UTC, ysakasin commented
思ったいたのよりだいぶ機能が増えたD66クラスが作成されましたが、奇遇判定を上も下も両対応するのは需要があるんでしょうか？　少なくとも寄稿してもらった範囲では最初のダイス1つを奇遇判定できればいい気がします。

両対応だとデータ構造が記述しづらかったり思いの外複雑になるので、できるだけシンプルに保ちたいです。

2020-12-26 04:46 UTC, ViVi-shark commented
> 少なくとも寄稿してもらった範囲では最初のダイス1つを奇遇判定できればいい気がします。

　これはそのとおりです。

> データ構造が記述しづらかったり

　これは `Hash` でも `Array` でも受けられるようにすればよかったかと思いつつ、

　それはそれとして、左ダイスと右ダイスでキーの解決方法を変えるほうが（コード上・クラス仕様として）複雑になるという考えであのようにしたのですが、 YAGNI 的に今回のダイスボットで必要なふるまいだけに変更しました。 https://github.com/bcdice/BCDice/pull/341/commits/a411f652baadf730eeecfeb846704db4c805639f

2020-12-26 04:53 UTC, ysakasin commented
> 左ダイスと右ダイスでキーの解決方法を変えるほうが（コード上・クラス仕様として）複雑になる

おっしゃる通りだと思います。その代償として、表の煩雑になるというトレードオフがありそうな気がします。


加えて質問ですが、コンストラクタを `def initialize(name, odd:, even:)` とせずに `def initialize(name, items)`とHashを受け取るようにしているのは何か思惑があるのでしょうか？

oddとevenは必要不可欠な要素なので、コンストラクタの引数として要求した方が、コンストラクタの引数情報から表作成に必要な情報が分かり、良いのではないかと感じました。

2020-12-26 04:57 UTC, ViVi-shark commented
> 加えて質問ですが、コンストラクタを def initialize(name, odd:, even:) とせずに def initialize(name, items)とHashを受け取るようにしているのは何か思惑があるのでしょうか？

　ほかのテーブル系（ `DiceTable::Table`, `DiceTable::D66Table` ）とインタフェースの傾向を合わせる意図です。

> oddとevenは必要不可欠な要素なので、コンストラクタの引数として要求した方が、コンストラクタの引数情報から表作成に必要な情報が分かり、良いのではないかと感じました。

　これもそのとおりだとは思うので、変更は可能です。

2020-12-26 05:07 UTC, ysakasin commented
`def initialize(name, odd:, even:)` に変更をお願いします。

`def initialize(name, items)`と書くとコンストラクタのインターフェースは一見同じように見えますが、実際は受け付けられる`items`の値が異なっているので、同じインターフェースにはなっていません。引数の数を合わせてもダックタイピングが成立しないので、読みやすさに舵を切った方が得られる恩恵が大きそうです。

先例をあげると、`RangeTable`もテーブル系のダックタイピングができるように各種メソッドが完備されていますが、コンストラクタの引数は必要な分だけ増えています

https://github.com/bcdice/BCDice/blob/master/lib/bcdice/dice_table/range_table.rb

2020-12-26 05:22 UTC, ViVi-shark commented
@ysakasin 

　変更しました。 https://github.com/bcdice/BCDice/pull/341/commits/224d1c22861470c87f3e8a4ffd9e1f6eba857715

2020-12-26 05:33 UTC, ysakasin approved these changes

2020-12-26 05:33 UTC, merged

2020-12-26 05:33 UTC, ysakasin commented
寄稿ありがとうございます！ マージしました。

多数の指摘にも根気強く対応してくださりありがとうございます。