SW2.5のモンストラスロアで追加された森羅魔法のダメージ算出ダイスに対応
bcdice/BCDice pull request #372
Opened 2021-01-24 10:21 UTC by h-mikisato

SW2.5のモンストラスロアで追加されたドルイド技能（森羅魔法）において、
一部魔法で特異なダメージ算出方法が追加されました。

威力決定の際に威力表を参照せず、2d6の出目の範囲に応じて

- 出目が2-6の時は「A+魔力」点のダメージ
- 出目が7-9の時は「B+魔力」点のダメージ
- 出目が10-12の時は「C+魔力」点のダメージ

という形でダメージを算出しています。このA、B、Cの値は、使用する魔法によって異なっています。

「ダメージ算出」であるという性質上加減算などが必要になり、 単純なダイス表で表現するのも難しいため、専用のダイスコマンドを実装いたしました。

2021-01-28 15:41 UTC, ysakasin requested changes
提案ありがとうございます！ コード上の問題がいくつかあるので、修正お願いします。

2021-01-28 15:41 UTC, ysakasin commented on lib/bcdice/game_system/SwordWorld2_5.rb
> +        when /dru\[(\d+),(\d+),(\d+)\].*/i
```suggestion
        when /^dru\[(\d+),(\d+),(\d+)\]/i
```

2021-01-28 15:41 UTC, ysakasin commented on lib/bcdice/game_system/SwordWorld2_5.rb
> +          power_list = (1..3).map { |i| Regexp.last_match(i).to_i }
```suggestion
          power_list = Regexp.last_match.captures.map(&:to_i)
```

`MatchData#captures` を使うのが良いかと思います。
https://docs.ruby-lang.org/ja/latest/class/MatchData.html#I_CAPTURES

2021-01-28 15:41 UTC, ysakasin commented on lib/bcdice/game_system/SwordWorld2_5.rb
> +        ].compact
```suggestion
        sequence = [
          "2D[#{dice_list.join(',')}]=#{power}",
          "#{power}#{Format.modifier(command.modify_number)}",
          total
        ]
```

配列にnilの要素がないので `Array#compact` を使う必要はありません

2021-01-29 11:34 UTC, ysakasin commented
出力ですが、以下のようにコマンドがわかるようにした方が良いと思うのですがどうでしょう。
最近新しくコマンドを作る際には、できるだけ入力内容が出力でわかるようにしています。

```
(Dru[4,7,13]+10) ＞ 2D[6,5]=13 ＞ 13+10 ＞ 23"
```

また、入力が`Dru[4,7,13]+5+5` のような時にも `(Dru[4,7,13]+10)` のように正規化されて表示されたら嬉しいです。

2021-02-10 12:35 UTC, ysakasin requested changes

2021-02-10 12:35 UTC, ysakasin commented on lib/bcdice/game_system/SwordWorld2_5.rb
> +          druid_parser = Command::Parser.new(DRUID_DICE_RE, round_type: BCDice::RoundType::CEIL)
`Command::Parser`に渡す正規表現で `^` を使うのは想定していないため、使いまわさずにリテラルで指定してください。

2021-02-10 12:35 UTC, ysakasin commented on lib/bcdice/game_system/SwordWorld2_5.rb
> +        when DRUID_DICE_RE
`Command::Parser` で使いまわさないため、定数で使いまわさずにリテラルを直接指定してください

2021-02-13 06:27 UTC, h-mikisato commented
ご連絡遅くなり申し訳ありません。レビュー部分反映させていただきました

2021-02-13 06:33 UTC, ysakasin approved these changes
LGTM!

2021-02-13 06:37 UTC, merged