ソード・ワールドの威力表ダイスを、
bcdice/BCDice pull request #373
Opened 2021-01-28 12:21 UTC by h-mikisato

2021-01-28 16:01 UTC, ysakasin requested changes
ありがとうございます！
まだ全部は見切れていませんが、nil関連の扱いについて気になった部分が多かったので、取り急ぎ解説しました。修正お願いします。

2021-01-29 13:35 UTC, ysakasin commented
修正値が順不同にかけて、合算されると言う仕様は今後の拡張に問題がありそうなので、従来の仕様に戻すようお願いします。
https://discord.com/channels/597133335243784192/597135607604445204/804705240146247712

2021-02-10 12:48 UTC, ysakasin commented
大枠はOKそうです。細々とした修正したいところが多々あるのであとはこちらで直します。 #372 とコンフリクトするだろうとのことなので、そちらをマージしてから手をつけます。

2021-02-25 12:04 UTC, ysakasin commented
@h-mikisato 気になった点をこちらで修正しました。そちらでも動作に影響していないか見ていただけると助かります。

2021-02-25 17:44 UTC, h-mikisato commented
承知しました。26日中には対応します。

2021-02-26 11:55 UTC, h-mikisato commented
コードの確認およびある程度のダイスをreplで振ってみました。挙動に関して問題なさそうです。ありがとうございます。

2021-02-26 14:03 UTC, ysakasin approved these changes

2021-02-26 14:04 UTC, merged

2021-02-26 14:04 UTC, ysakasin commented
@h-mikisato ありがとうございます。マージしました。