冒険企画局版の歯車の塔の探空士実装
bcdice/BCDice pull request #414
Opened 2021-04-12 16:00 UTC by GenKuzumochi

* 歯車の塔の探空士 基本ルールブックを実装
* 旧版のタイトルとソートキーを調整

- [ ] テスト

2021-04-17 15:18 UTC, GenKuzumochi commented
とりあえず一通り実装しました、レビューお願いいたします。

2021-04-19 11:39 UTC, ysakasin requested changes
ありがとうございます！
細かいところですが何点かコメントしました。
加えて、全てのメソッドをpublicにするのではなく、適宜 `private` を入れるように変更お願いします。

2021-04-19 11:39 UTC, ysakasin commented on lib/bcdice/game_system/SkynautsBouken.rb
> +                             .enable_fumble.enable_critical.parse(command)
確認した範囲ではクリティカル値の変動はないと思いますので、 `enable_critical` は省いてください

2021-04-19 11:39 UTC, ysakasin commented on lib/bcdice/game_system/SkynautsBouken.rb
> +      D_REGEXP = %r{^D([12346789]{0,8})(\[.+\]|S|F|SF|FS)?/(\d{1,2})(@([2468]))?$}.freeze
```suggestion
      D_REGEXP = %r{^D([1-9]{0,8})(\[.+\]|S|F|SF|FS)?/(\d{1,2})(@([2468]))?$}.freeze
```

2021-04-19 12:45 UTC, GenKuzumochi commented on lib/bcdice/game_system/SkynautsBouken.rb
> +      D_REGEXP = %r{^D([12346789]{0,8})(\[.+\]|S|F|SF|FS)?/(\d{1,2})(@([2468]))?$}.freeze
5は来ないため、[1-46-9]のつもりで書いていました。どの表記がいいですかね？

* [12346789]
* [1-46-9]
* [1-9] (5は弾くなり無視する）

2021-04-20 11:24 UTC, ysakasin requested changes

2021-04-20 11:24 UTC, ysakasin commented on lib/bcdice/game_system/SkynautsBouken.rb
> +            "失敗にイライラしてしまった。キミた獲得している【キズナ】1つの「支援チェック」にチェックを入れる。",
誤植だと思われるので確認お願いします。

2021-04-21 13:01 UTC, ysakasin approved these changes
LGTM!

2021-04-21 13:01 UTC, merged