[StellarKnights] success/failure を明示
bcdice/BCDice pull request #425
Opened 2021-04-20 19:14 UTC by ViVi-shark

#423 

---

# 対象

　成功／失敗の概念があるのは、【アタック判定】に防御力との比較が指定された場合のみであるはず。

# 方針

　当該の【アタック判定】において、成功数が１以上ならば成功、成功数が０ならば失敗とみなす。

　基本ルールブック『銀剣のステラナイツ』の時点では「失敗」という表現はもちいられていないが（同書p150）、『銀剣のステラナイツ　星屑のリヴラガーデン』p119では同じ意味合いの処理に対して「失敗」という表現がされているため、この方針で妥当だと考える。

# 備考

　成功数が 0 になるテストケースがもともとなかったので、それも追加してある。

2021-04-21 11:09 UTC, ysakasin requested changes
ありがとうございます！ テストデータの部分にコメントしましたので修正お願いします。

2021-04-21 11:09 UTC, ysakasin commented on test/data/StellarKnights.toml
> +failure = false
```suggestion
```
何も書かない場合にはfalse扱いとなるため、書かなくてOKです

2021-04-21 11:09 UTC, ysakasin commented on test/data/StellarKnights.toml
> +failure = false
```suggestion
```

2021-04-21 22:51 UTC, ViVi-shark commented
@ysakasin 

　ご確認ありがとうございます。そのまま採用しました。

2021-04-22 10:07 UTC, ysakasin approved these changes
ありがとうございます！

2021-04-22 10:07 UTC, merged