BattleTech: CDxコマンドを改良する
bcdice/BCDice pull request #445
Opened 2021-04-30 03:53 UTC by ochaochaocha3

バトルテックのメック戦士意識維持ロール（`CDx`）を改良しました。

* 2018年発行の「BattleTech: A Game of Armored Combat」p. 44に合わせて、識別子名や処理を改良しました。
* 結果のテキストを分かりやすくしました。
    * ダメージ6はロールなしで「死亡」、ダメージ1〜5は2D6の成功判定、とやや複雑な処理だったため、最近のゲームシステムを参考にして結果のテキストを詳しくしました。
    * 例1（`CD3`）：`7[5,2]>=7 ＞ 成功` → `CD3 ＞ (2D6>=7) ＞ 7[5,2] ＞ 7 ＞ 成功`
    * 例2（`CD6`）：`死亡` → `CD6 ＞ 死亡`
* 結果に成功、失敗、ファンブルを含めました。`CD6` のときはファンブルかつ失敗、`CD1` 〜 `CD5` のときは成功または失敗となります。

2021-05-04 00:36 UTC, ysakasin requested changes

2021-05-04 00:36 UTC, ysakasin commented on lib/bcdice/game_system/BattleTech.rb
> +        values_str = @randomizer.rand_results.map(&:first).join(",")
`@randomizer` はRepeatコマンドで同じインスタンスが使いまわされるので、 `Rnadomizer#rand_results` から出目の情報を取得すると意図しない状況になることがあります。`Randomizer#roll_barabara` でロールしてそこから合計値を出力するようにしてください。

2021-05-04 02:24 UTC, ochaochaocha3 commented
> `@randomizer` はRepeatコマンドで同じインスタンスが使いまわされるので、 `Rnadomizer#rand_results` から出目の情報を取得すると意図しない状況になることがあります。`Randomizer#roll_barabara` でロールしてそこから合計値を出力するようにしてください。

おっと、これには気づいてませんでした。そのように変えます。

今回のように `roll_sum` で合計値とともに各出目も取得することは頻出なので、今後Randomizer側で詳しく結果を得られるメソッドを用意する（互換性維持のため、例えば `Randomizer#roll_sum_with_details` のような名前で追加する）のを検討してもいいかもしれません。

2021-05-04 02:59 UTC, ochaochaocha3 commented on lib/bcdice/game_system/BattleTech.rb
> +        values_str = @randomizer.rand_results.map(&:first).join(",")
35579e34ef2fa89e66780b93a16c82489d6d498a 修正しました。

2021-05-08 00:29 UTC, ysakasin approved these changes

2021-05-08 00:29 UTC, merged