[Irisbane] 『瞳逸らさぬイリスベイン』のダイスボットを作成
bcdice/BCDice pull request #482
Opened 2021-06-25 10:19 UTC by ViVi-shark

# ゲームシステム

　『瞳逸らさぬイリスベイン』（著：木野目理兵衛／どらこにあん，新紀元社刊）。
　電子書籍版は 2021/06/25 現時点でリリース済み、物理書籍版の公式発売日は 2021/06/26 。

* [どらこにあん](https://www.dracotrpg.com/irisbane)
* [Amazon](https://www.amazon.co.jp/%E7%9E%B3%E9%80%B8%E3%82%89%E3%81%95%E3%81%AC%E3%82%A4%E3%83%AA%E3%82%B9%E3%83%99%E3%82%A4%E3%83%B3-Role-Roll-Books-%E6%9C%A8%E9%87%8E%E7%9B%AE%E7%90%86%E5%85%B5%E8%A1%9B-ebook/dp/B097DKFQFT/)
* [新紀元社](http://www.shinkigensha.co.jp/book/978-4-7753-1936-9/)

# 機能

* 「攻撃判定」（ルールブックp146）の処理
* 上記専用コマンドを使わずにバラバラダイスで原始的に処理するケースを考慮して、バラバラダイスをソートする設定
* 端数処理を切り上げに設定（ルールブックp54）

## 攻撃判定のインタフェースについて

```
        ■攻撃判定（ ATTACKx,y,z ）
        x: 攻撃力
        y: 判定数
        z: 目標値
        （※ ATTACK は ATK または AT と簡略化可能）
        例） ATTACK2,3,5
        例） ATK10,2,4
        例） AT8,3,2
```

　ルールブック内では「【攻撃力：Ｘ　判定数：Ｙ　目標値：Ｚ】の攻撃判定を行う」という書式で表記される。
　ルール記述からコマンドに起こす際に、数値の順序が入れ替わらないことを重視した。

　数値の意味を踏まえて `ATTACKx*(yD<=z)` などとする案もあったが、タイピング量がかさむことと、数式としての乗算との混同の可能性を考慮して、単純なカンマ区切りにした。

2021-07-13 11:48 UTC, ysakasin commented
@ViVi-shark レビューがだいぶ遅くなりすみません。

コマンドの形式ですが、できればカンマで引数を区切っていく方式は避けたいです。理由はいくつかあり、一つはコマンドから入力内容の推測は判別がしづらくなること、次に何個目の数が何を示すのかわかりずらいこと、最後に今後引数を増やしたくなってしまった時に余計煩雑になるためです。

カンマ区切りで複雑化してしまった例としては、新クトゥルフ神話TRPGの自動火器コマンドがあります。

目標値zは `<=z` にするとして、xとyの記述方法に何か良いアイディアはないでしょうか？

2021-07-13 12:08 UTC, ViVi-shark commented
@ysakasin 

　ダイスボットのインタフェースの問題というよりは元ルールが本質的に有する複雑度の問題だとおもいますが、仰有ることは理解できます。

---

　プリフィックス＋値（または値＋サフィックス）の形式だといかがでしょうか？（これは実在しないルールですが、たとえば「クリティカル値５」を「c5」（または「5c」）と指定するようなイメージ）

　ルール上に存在するパラメタが「攻撃力」「判定数」「目標値」で、「判定数」がダイスの数をあらわすので、（文字を D として） Dx よりは xD のほうが慣例に沿う……と考えるとプリフィックスよりはサフィックスでしょうか。この方針だと、

* 攻撃力 → 係数として使うので coefficient → c
* 判定数 → ダイス数として使うので dices → d
* 目標値 → 閾値として使うので threshold → t

　として、 `ATTACKxCyDzT` みたいな形式になります。（パラメタの順序は問わない実装にしそうな気がしますが）

　……と提案はしてみましたが、判読しづらい、前の文字と後の文字のどっちにくっつくのかわかりづらい、みたいな問題が容易に想像されて、あんまり改善されていないですね……。

　これよりは `ATTACKc=x,d=y,t=z` みたいな方向性のほうがマシかもしれません。（順序を問わなければ入力内容の判別のしやすさ、パラメタの意味のわかりやすさ、拡張性の容易さのすべてにおいてまぁまぁ改善される）

---

　それか、乗算記号の混同を顧みず（パース自体はやろうとおもえばできますし） `ATTACKx*(yD<=z)` 案でいくのもアリかとはおもいます。

　`*` の代わりに `x` や `**` や `#` あたりの（[四則演算コマンド](https://docs.bcdice.org/arithmetic.html)でつかわない）文字列にする手もあります。

2021-07-13 12:16 UTC, ViVi-shark commented
　`x#y<=z` か `x**y<=z` がいちばんマシな気がしてきました。

2021-07-13 12:17 UTC, ysakasin commented
`ATTACKxCyDzT` みたいな見辛さは従来では記号で解決することにしていて、プレフィックスとしてはアルファベットではなく`@`や`#`を採用しています。

PRの説明にも書いてくださった通り順序にこだわってらっしゃるのは承知で提案しますが、
`yAD@x<=z` のような形式はどうでしょうか `AD`や`@`は変更の余地があるとは思います。
上げてくださった`ATTACKx#y<=z` のような形式でも良いと思います。

2021-07-13 12:37 UTC, ViVi-shark commented
@ysakasin 

　入力の便宜としてもニュアンスとしても `#` より `@` のほうがよさそうなので、

　`ATTACKx@y<=z` でどうでしょう？

2021-07-13 12:42 UTC, ysakasin commented
@ViVi-shark `ATTACKx@y<=z` で良いと思います！

2021-07-13 13:12 UTC, ViVi-shark commented
@ysakasin 

　`ATTACKx@y<=z` に変更しました。 https://github.com/bcdice/BCDice/pull/482/commits/443f32a4635dc72b15cd3d8dfbc0305ad7b6098e

2021-07-14 12:45 UTC, ysakasin commented
@ViVi-shark 修正ありがとうございます。見た限り、コードの方は問題ないと思います。

表についてなのですが、以下の表は一見するとキャラクター作成に使うような表に見えますが、セッション中に使うものでしょうか？ プレイ中に使うものであれば何ら問題ありません。

ご存知かと思いますが、BCDiceでは表類はセッション中に使うもののみサポートし、キャラクター作成に使う類のものは実装しない方針です。


```
        ■シルエットライン（p37）
        SilhouetteLineEye, SilhouetteLEye, SLineEye, SLEye 瞳の印象
        SilhouetteLineHair, SilhouetteLHair, SLineHair, SLHair 髪の長さ
        SilhouetteLineHeight, SilhouetteLHeight, SLineHeight, SLHeight 身長
        SilhouetteLineCon, SilhouetteLCon, SLineCon, SLCon 体型
        SilhouetteLineDress, SilhouetteLDress, SLineDress, SLDress 服飾
        SilhouetteLineTint, SilhouetteLTint, SLineTint, SLTint 色彩

        ■そのほかの表
        CAge 年齢（p27）
        CGender 性別（p27）
        CFailure 欠落（p30）
        CDesire 願望（p31）
        CQuestion 問い掛け（p34-35）
        CEndblessStyle, CEndStyle 復讐者のスタイル（p40）
        CEmblaceStyle, CEmbStyle 掌握者のスタイル（p41）
        ExpectExecution, EEx 望む執行の方向性（p48）
```

2021-07-14 13:11 UTC, ViVi-shark commented
@ysakasin 

　仰有るとおり、一義的にはキャラクター作成に使う表です。

　ただ、ゲームとして、セッションの進行中にキャラクター（ＮＰＣ）のディティールを突発的に決定する必要がしばしば発生する（「ボスと戦う」以外のすべての展開がプレイヤーのアドリブに任されている）性質があり、キャラクター作成関連の表をプレイ中に使いたいケースがままあるかと考えています。
　（ゲームルール上の確固たる根拠ではなく、実際のプレイにおけるユースケースへの考慮です）

　[ステラナイツの表](https://github.com/bcdice/BCDice/pull/107)（のうち“シチュエーション表”でないもの）がアリならアリかなという考えです。

2021-07-14 13:23 UTC, ysakasin commented
@ViVi-shark 

なるほど。そういう用途でしたら削除でお願いします。
わざわざ文字起こししてもらったのにすみません。

銀剣のステラナイツの表は特殊な事情により掲載しているため、BCDiceの表掲載に関するルールの外にいます。

2021-07-14 13:36 UTC, ViVi-shark commented
@ysakasin 

　そのようにしました https://github.com/bcdice/BCDice/pull/482/commits/7a9650c3165ae0252c6f8d27be98d58ab881af22

2021-07-14 13:43 UTC, ysakasin requested changes
結果的に `ParityTable` も未使用になってしまったため、こちらもテスト含め関連ファイルの削除をお願いします。

2021-07-14 13:48 UTC, ViVi-shark commented
> 結果的に `ParityTable` も未使用になってしまったため、こちらもテスト含め関連ファイルの削除をお願いします。

　revert しました https://github.com/bcdice/BCDice/pull/482/commits/96558af16d2a6f696376c178703e57aebfd41c69

2021-07-14 13:54 UTC, ysakasin approved these changes

2021-07-14 13:54 UTC, merged

2021-07-14 13:54 UTC, ysakasin commented
@ViVi-shark ありがとうございます！　マージしました！！