[CastleInGray] 『灰色城綺譚』 CASTLE IN GRAY The Haunted Palace
bcdice/BCDice pull request #495
Opened 2021-08-20 12:29 UTC by reismannnr2

### ゲームシステム
灰色城綺譚
CASTLE IN GRAY The Haunted Palace

発行: かりかりうめ

## 関連サイト
[かりかりうめ](https://www.karikariume.com/)
[公式ショップ](https://kkurpg.thebase.in/)

## コマンド内容

        ■ 色占い (BnWm)
        n: 黒
        m: 白
        n, m は1～12の異なる整数

        例) B12W7
        例) B5W12

        ■ 悪意の渦による占い (MALn)
        n: 悪意の渦
        n は1～12の整数

        ■ その他
        ・感情表 ET
        ・暗示表(黒) BIT
        ・暗示表(白) WIT

- [x] 判定用コマンドの実装
- [x] 各種表の追加

ルール自体は非常に簡潔なシステムですが、オンセだと判定が少しややこしいので作成しました。

2021-08-20 13:20 UTC, ysakasin requested changes
寄稿ありがとうございます。

`DiceTable::Table` で追加したコマンドが実行できるか、確認するテストケースを追加してください。

2021-08-20 13:35 UTC, reismannnr2 commented
すみません、追加しておきました。

2021-08-20 14:00 UTC, ysakasin requested changes
表テストの追加ありがとうございます。

表のテストですが、全パターンの網羅はしないでください。
各コマンドごとに３パターンほどに抑えてください。

2021-08-20 14:12 UTC, reismannnr2 commented
迅速な再チェックありがとうございます、両端と中間値のテストに削減しました。

2021-08-20 15:27 UTC, ysakasin reviewed
修正ありがとうございます。
こちらで細かな修正を行ってから取り込もうと思います！

2021-08-21 00:49 UTC, ysakasin commented
@reismannnr2 `BnWm` の色を判定する条件式を修正しました。問題ないか確認お願いします。

2021-08-23 13:11 UTC, reismannnr2 commented
確認しました！ 大丈夫だと思います！

2021-08-23 13:46 UTC, ysakasin approved these changes

2021-08-23 13:47 UTC, merged