[Monotone Museum Korean] Update newly added results
bcdice/BCDice pull request #518
Opened 2021-11-29 03:40 UTC by jbblily

Translated newly added chart result. Please take a look if it has any problem. Thank you.

2021-11-29 14:06 UTC, ochaochaocha3 requested changes

2021-11-29 14:06 UTC, ochaochaocha3 commented on i18n/MonotoneMuseum/ko_kr.yml
> +        ＞ 애프터 플레이에서 기본박탈치를 +3할 것. (상한9). 대가를지불할 수 있는지는 박탈체크시에 확정할 것.
This line seems to be indented one level too shallow, resulting in a syntax error. Please fix it.
```suggestion
          ＞ 애프터 플레이에서 기본박탈치를 +3할 것. (상한9). 대가를지불할 수 있는지는 박탈체크시에 확정할 것.
```

2021-11-30 13:48 UTC, ochaochaocha3 requested changes
Some tests have failed due to the syntax error in `test/data/MonotoneMuseum_Korean.toml` and trailing spaces in `i18n/MonotoneMuseum/ko_kr.yml`. Please confirm these files.

2021-11-30 13:48 UTC, ochaochaocha3 commented on test/data/MonotoneMuseum_Korean.toml
> +output = "일그러짐표(바다)(56) ＞ 【술의 바다】\n바닷물이 술이 된다. 물을 마신 모든 것은 취해 이성을 잃는다. 그 모습이 마치 암흑기에 멸망한 "나태의 고도"를 연상시킨다."
The `"`s inside a string must be escaped, or please use `“...”` (fullwidth quotation marks) as in Japanese output.

2021-11-30 13:48 UTC, ochaochaocha3 commented on i18n/MonotoneMuseum/ko_kr.yml
> +          당신은 배드스테이터스 [중압]을 받는다.
Test for this value failed:

```
<"징조표(6) ＞ 【중압】\n" + "배드 스테이터스［중압］을 받는다."> expected but was
<"징조표(6) ＞ 【중압】\n" + "당신은 배드스테이터스 [중압]을 받는다.">
```

Probably, the test case is not updated.

2021-11-30 13:48 UTC, ochaochaocha3 commented on i18n/MonotoneMuseum/ko_kr.yml
> +          가람이 낳은 절망과 공포가 배어 씬 내의 모든 엑스트라는 모종의 이형화를 받는다. 이것을 치료할 주술은 없다. 이형의 무리 (IZ P237) * 1D6과 전투시켜도 좋다.
The trailing space should be removed.

```suggestion
          가람이 낳은 절망과 공포가 배어 씬 내의 모든 엑스트라는 모종의 이형화를 받는다. 이것을 치료할 주술은 없다. 이형의 무리 (IZ P237) * 1D6과 전투시켜도 좋다.
```

2021-11-30 13:48 UTC, ochaochaocha3 commented on i18n/MonotoneMuseum/ko_kr.yml
> +          사람들의 마음에 허무가 퍼져 불안과 절망이 가득 차오른다. 도망칠 수 없는 공포로부터 도망치기 위해 사람들은 스스로, 혹은 무의식적으로 죽음으로 향하는 행동을 시작한다.
The trailing space should be removed.

```suggestion
          사람들의 마음에 허무가 퍼져 불안과 절망이 가득 차오른다. 도망칠 수 없는 공포로부터 도망치기 위해 사람들은 스스로, 혹은 무의식적으로 죽음으로 향하는 행동을 시작한다.
```

2021-11-30 13:48 UTC, ochaochaocha3 commented on i18n/MonotoneMuseum/ko_kr.yml
> +          시간이 국지적으로 역류한다. 씬 내에 존재하는 여러 무생물과 생물은 2d6년 전으로 돌아간다. 생물이라면 젊어진다. 이 결과, 제조년/출생년도 보다 전으로 돌아갔을 경우에는 허무에 삼켜저 소멸한다. 실 잣는 이는 【재봉】난이도 8의 판정에 성공하면 이 영향을 받지 않는다.
The trailing space should be removed.

```suggestion
          시간이 국지적으로 역류한다. 씬 내에 존재하는 여러 무생물과 생물은 2d6년 전으로 돌아간다. 생물이라면 젊어진다. 이 결과, 제조년/출생년도 보다 전으로 돌아갔을 경우에는 허무에 삼켜저 소멸한다. 실 잣는 이는 【재봉】난이도 8의 판정에 성공하면 이 영향을 받지 않는다.
```

2021-11-30 13:48 UTC, ochaochaocha3 commented on i18n/MonotoneMuseum/ko_kr.yml
> +          일그러짐과 올풀림의 발생을 사람들이 깨닫고, 이 재앙을 피하려면 이형을 불길에 태워야 한다고 외치기 시작한다. PC들이 실 잣는 이라는 것이 알려지면 PC들도 화형대로 보내질 것이다.
The trailing space should be removed.
```suggestion
          일그러짐과 올풀림의 발생을 사람들이 깨닫고, 이 재앙을 피하려면 이형을 불길에 태워야 한다고 외치기 시작한다. PC들이 실 잣는 이라는 것이 알려지면 PC들도 화형대로 보내질 것이다.
```

2021-11-30 13:48 UTC, ochaochaocha3 commented on i18n/MonotoneMuseum/ko_kr.yml
> +          쥐 떼가 출현해 곡물을 먹어치우고 역병을 퍼뜨린다. 어린이나 노인이라면 물어 죽일 것이다. 큰 쥐(MM P240)*1D6 마리와 전투를 벌이게 해도 된다.
The trailing space should be removed.

```suggestion
          쥐 떼가 출현해 곡물을 먹어치우고 역병을 퍼뜨린다. 어린이나 노인이라면 물어 죽일 것이다. 큰 쥐(MM P240)*1D6 마리와 전투를 벌이게 해도 된다.
```

2021-11-30 13:48 UTC, ochaochaocha3 commented on i18n/MonotoneMuseum/ko_kr.yml
> +          씬에 등장해있는 실잣는이가 아닌 NPC 한 명이 칠흑의 흉수 (MM 240p)로 변신한다.
The trailing space should be removed.
```suggestion
          씬에 등장해있는 실잣는이가 아닌 NPC 한 명이 칠흑의 흉수 (MM 240p)로 변신한다.
```

2021-11-30 13:48 UTC, ochaochaocha3 commented on i18n/MonotoneMuseum/ko_kr.yml
> +          다음 씬 이후 엑스트라는 일절 등장하지 않는다. 연극의 무대가 된 장소에서 동물이나 인간의 모습이 존재하지 않게 된다.
The trailing space should be removed.
```suggestion
          다음 씬 이후 엑스트라는 일절 등장하지 않는다. 연극의 무대가 된 장소에서 동물이나 인간의 모습이 존재하지 않게 된다.
```

2021-11-30 13:48 UTC, ochaochaocha3 commented on i18n/MonotoneMuseum/ko_kr.yml
> +          유리가 깨지는 소리가 나며, 당신도 깨져간다. 당신은 2D6+캐릭터레벨 점의 【HP】를 잃는다.
The trailing space should be removed.
```suggestion
          유리가 깨지는 소리가 나며, 당신도 깨져간다. 당신은 2D6+캐릭터레벨 점의 【HP】를 잃는다.
```

2021-11-30 13:48 UTC, ochaochaocha3 commented on i18n/MonotoneMuseum/ko_kr.yml
> +          이탈능력을 사용한 결과로 징조표를 굴리게 되었을 경우에만 적용한다 (그렇지 않을 경우 다시 굴린다). 이 표를 굴리는 원인이 된 이탈능력을 이 라운드 (전투중이 아니라면 씬 동안) 동안 더 이상 사용할 수 없다.
The trailing space should be removed.
```suggestion
          이탈능력을 사용한 결과로 징조표를 굴리게 되었을 경우에만 적용한다 (그렇지 않을 경우 다시 굴린다). 이 표를 굴리는 원인이 된 이탈능력을 이 라운드 (전투중이 아니라면 씬 동안) 동안 더 이상 사용할 수 없다.
```

2021-11-30 13:48 UTC, ochaochaocha3 commented on i18n/MonotoneMuseum/ko_kr.yml
> +          세계는 기묘하도록 아름답다. 물에는 물고기 한 마리 없고 덤불에는 벌레 한 마리 없다. 하늘에는 새가 날지 않는다. 기분나쁜 정적이 세계를 감싼다.
The trailing space (tab) should be removed.
```suggestion
          세계는 기묘하도록 아름답다. 물에는 물고기 한 마리 없고 덤불에는 벌레 한 마리 없다. 하늘에는 새가 날지 않는다. 기분나쁜 정적이 세계를 감싼다.
```

2021-11-30 13:48 UTC, ochaochaocha3 commented on i18n/MonotoneMuseum/ko_kr.yml
> +          세계가 칠흑과 둔백으로 덧칠된다. 씬 내에 존재하는 여러 무생물과 생물이 흑백의 모노톤이 된다. 실잣는이는 【재봉】 난이도 8의 판정에 성공하면 이 영향을 받지 않아도 좋다.
The trailing space should be removed.
```suggestion
          세계가 칠흑과 둔백으로 덧칠된다. 씬 내에 존재하는 여러 무생물과 생물이 흑백의 모노톤이 된다. 실잣는이는 【재봉】 난이도 8의 판정에 성공하면 이 영향을 받지 않아도 좋다.
```

2021-11-30 13:48 UTC, ochaochaocha3 commented on i18n/MonotoneMuseum/ko_kr.yml
> +          바닷물이 칠흑으로 변한다. 바다 속에 있으면 한 치 앞도 보이지 않는다. [구분 : 사격]의 무기에 의한 공격의 펌블치가 +5된다.
The trailing space (tab) should be removed.
```suggestion
          바닷물이 칠흑으로 변한다. 바다 속에 있으면 한 치 앞도 보이지 않는다. [구분 : 사격]의 무기에 의한 공격의 펌블치가 +5된다.
```

2021-11-30 13:48 UTC, ochaochaocha3 commented on i18n/MonotoneMuseum/ko_kr.yml
> +          바닷물이 술이 된다. 물을 마신 모든 것은 취해 이성을 잃는다. 그 모습이 마치 암흑기에 멸망한 "나태의 고도"를 연상시킨다.
The trailing space (tab) should be removed.
```suggestion
          바닷물이 술이 된다. 물을 마신 모든 것은 취해 이성을 잃는다. 그 모습이 마치 암흑기에 멸망한 "나태의 고도"를 연상시킨다.
```

2021-11-30 13:48 UTC, ochaochaocha3 commented on i18n/MonotoneMuseum/ko_kr.yml
> +          당신의 등에 오한과 가려움이 일고, 칠흑의 날개가 피어난다. 이 연극 중, 당신은 마이너 액션으로 박탈치 1을 상승시켜 비행상태가 된다. (해제에도 마이너 액션 사용)
The trailing space should be removed.
```suggestion
          당신의 등에 오한과 가려움이 일고, 칠흑의 날개가 피어난다. 이 연극 중, 당신은 마이너 액션으로 박탈치 1을 상승시켜 비행상태가 된다. (해제에도 마이너 액션 사용)
```

2021-12-01 03:32 UTC, jbblily commented
Sorry for lots of errors... I deleted all the tabs at the end of the sentences, and also some typos not matching to test script. 
I hope it helps...

2021-12-01 12:21 UTC, ochaochaocha3 approved these changes
Your fixes seem good to me. Thank you for your cooperation!

2021-12-01 12:22 UTC, merged

2021-12-01 12:22 UTC, ysakasin commented
@jbblily Awesome work! Thanks!