ダークデイズドライブ拡張
bcdice/BCDice pull request #531
Opened 2022-02-05 12:17 UTC by GenKuzumochi

・サプリに対応（センターの行動決定、対話ダメージ表）
・ページ数を明記（ルールブックのテキストを参照しやすいように）
・イケメンアクション決定表→イケメンアクション表を連続でふるコマンド`IAX`追加

https://bouken.jp/pd/d3/

2022-02-28 00:51 UTC, ysakasin requested changes

2022-02-28 00:51 UTC, ysakasin commented on lib/bcdice/game_system/DarkDaysDrive.rb
> +        m = ia.body.match(/\((.+?)\)/)
```suggestion
        m = ia.body.match(/\(([A-Z]+)\)/)
```
より細かい指定にした方が良さそうに思えました

2022-03-20 16:08 UTC, GenKuzumochi commented
多忙で反応が遅れました。ご提案をそのままAcceptしました。

2022-03-28 04:48 UTC, ysakasin approved these changes
:+1:

2022-03-28 04:48 UTC, merged