『幻想和風ＲＰＧ　不知火』のダイスボットを追加
bcdice/BCDice pull request #533
Opened 2022-02-07 09:37 UTC by ViVi-shark

# ゲームについて

『幻想和風ＲＰＧ　不知火』（著：小林正親と歌風座，刊：新紀元社）

* [Role&Roll](http://r-r.arclight.co.jp/rpg/shiranui)
* [Amazon](https://www.amazon.co.jp/%E5%92%8C%E9%A2%A8%E5%B9%BB%E6%83%B3RPG-%E4%B8%8D%E7%9F%A5%E7%81%AB-Role-Roll-RPG-ebook/dp/B09QXHK4S1/)
* ISBN-13: 978-4775319437

# サポートした機能

## ∞D66

このゲーム固有のダイスロール方法「∞D66」（ルールブックp40）の基本形を実装しました。

### 書式

書式は、

* `∞D66`
* `ID66`
* `x+∞D66` （ `x` は固定値）
* `x+ID66` （ `x` は固定値）

としました。

「∞D66」はルールブックの表記に則った記法として、「ID66」は簡易記法として提供しています。
固定値を左側に置くのは、ルールブックの表記（p40など）に合わせる意図によります。

### 結果

ゲームルールとして「成功」「失敗」「クリティカル」「ファンブル」は存在しませんが、ニュアンスをふまえて次のとおりに対応させています。

* 成功：対応ケースなし
* 失敗：「しくじり」に該当するケース
* クリティカル：一度でも振り足しが発生したケース
* ファンブル：「しくじり」に該当するケース

# サポートしなかった機能

## チャート類

量が膨大なのと、くわえて「機械的に参照する以外の運用」が想定されるゲームルールであるため、いまのところサポートしていません。

（機械的に運用できるものだけ、追って別の pull request で追加するかもしれませんが）

## 「∞D66」に「鬼火」を使用するケース（ルールブックp44～45）

機械的に解決できないルール（ゲーム状況を見て、プレイヤーがインタラクティブに判断しながら解決する必要があるルール）なので、サポートしていません。

実プレイ上は、共通コマンドの `xB6` を利用することになると思います。

2022-03-07 13:10 UTC, ysakasin requested changes

2022-03-07 13:10 UTC, ysakasin commented on lib/bcdice/game_system/Shiranui.rb
> +          fixed_score = m[1].nil? ? nil : m[1].to_i
```suggestion
          fixed_score = m[1]&.to_i
```

[safe navigation operator `&.`](https://docs.ruby-lang.org/ja/latest/doc/news=2f2_3_0.html) を使うと良さそうです。

2022-03-07 14:43 UTC, ViVi-shark commented on lib/bcdice/game_system/Shiranui.rb
> +          fixed_score = m[1].nil? ? nil : m[1].to_i
ありがとうございます。そのまま採用しました。 https://github.com/bcdice/BCDice/pull/533/commits/011051db0b132cf8e70e4c1c182048d9fe267fbf

2022-03-07 14:44 UTC, ViVi-shark commented
いただいたコメントとはまったく関係ありませんが、セッションでしばらく実用してほしくなった機能があるので追加します。

2022-03-07 23:38 UTC, ysakasin requested changes

2022-03-07 23:38 UTC, ysakasin commented on lib/bcdice/game_system/Shiranui.rb
> +      }.transform_keys(&:upcase).freeze
```suggestion
      }.freeze
```

すでに大文字なので、キーの変換は不要です

2022-03-08 03:19 UTC, ViVi-shark commented on lib/bcdice/game_system/Shiranui.rb
> +      }.transform_keys(&:upcase).freeze
そのまま採用しました https://github.com/bcdice/BCDice/pull/533/commits/9b4c5775a5e40e93b2a5f0886e816d173a28f044

2022-03-08 13:22 UTC, ysakasin approved these changes

2022-03-08 13:23 UTC, merged

2022-03-08 13:23 UTC, ysakasin commented
PRありがとうございます！ マージしました。