寄稿：ゲームシステムの追加「サイバーパンクRED」
bcdice/BCDice pull request #540
Opened 2022-03-31 14:28 UTC by saronpasu

新規にダイスボットを寄稿します。
対象のルールは「サイバーパンクRED」です。
[公式サイト](https://hj-cyberpunk.com/)

主な判定ダイスは「CP+x+y+z>=t」としています。
x　能力値
y　技能
z　修正値
t　難易度

難易度より大きい場合に成功
出目10で決定的成功、1回のみ追加ダイスを振り、その値だけ加算します。
出目1で決定的失敗、1回のみ追加ダイスを振り、その値だけ減算します。

頻繁に使うことを考えて、イニシアティブロールのコマンド「INIx」も備えました。
各種ランダム表については、ダイスボットだけでプレイ可能にならないように表の結果詳細については、ルールのページ参照する形にしたのと
キャラメイクに関わるランダム表はほとんど掲載していません。

また、一部の表には初版のためか誤植と思われる不整合がありました。
ルール準拠で実装するとエラーになるため、動作するように変更しています。

・ナイトシティにおける夜間の遭遇表
　ルールP.421-422
ルール記載では、出目：70-72が「ソロのチーム」結果となっていますが
出目：72-77は「ブースターギャング」結果となっており、ランダム表の72が２つの結果となるように重複しています。
このまま実装するとエラーになるため、出目：73-77、結果「ブースターギャング」となるように修正しています。

・ナイトマーケット表
　ルールP.338
1D100のランダム表ですが、出目：0-5と、出目：96-100の項目がありました。
注釈として「00は100とみなす」と但書があったので、こちらの表については
出目100の場合のみ、出目：0-5の結果と、出目：96-100の結果をどちらも選べるように表示しています。

誤植訂正が公開されたら、修正するつもりです。
よろしくおねがいします。

2022-04-01 14:47 UTC, GenKuzumochi commented
素早い寄稿お疲れ様です！該当ルールブックを所持していないので、誤りがあったらすいません。

BCDiceでは、`CP+x>=t`か`CPx>=t`の形式でまとめてしまうのが一般的かと思います。
```
x　固定値（能力値、技能、修正値）
t　難易度
```
足し算はArithmeticEvaluator.evalを使うか、Command::Parserでいい感じにできるかと思います。

単純に数字を取るところは、シンプルにしたほうが見通しがよいかと思います。
（ルールの追加改正があればバッサリ書き換え）
```
ABI_RE = /(\d+)/.freeze
ABI_RE.match(cp_match[:ability])[1].to_i if cp_match[:ability]
↓
cp_match[:ability].to_i
```

2022-04-01 14:48 UTC, GenKuzumochi commented on test/data/CyberpunkRed.toml
> +  { sides = 6, value = 2 }
`,`が必要です。
（なんでCIが通過してるんだろう…）

2022-04-07 08:21 UTC, saronpasu commented
CPx>=t にまとめる形と、 Command::Parser を使うように修正しました。
それと、 Result の使い方が間違えていたようでしたので、そちらも合わせて修正しました。

2022-04-08 09:51 UTC, GenKuzumochi reviewed
見通しが良くなったかと思います！
また一部コメントつけました。好みが分かれる箇所もあるかと思うので、適宜無視してください。

2022-04-08 09:51 UTC, GenKuzumochi commented on lib/bcdice/game_system/CyberpunkRed.rb
> +        result.text += "+#{modify_number}" unless modify_number.zero?
modify_numberがマイナスになることは無いでしょうか？
負の可能性があるなら、`Format.modifier`がいい感じに処理してくれます。

2022-04-08 09:51 UTC, GenKuzumochi commented on lib/bcdice/game_system/CyberpunkRed.rb
> +        return result.text
`result`自体を返す必要があります。また、テストケースもクリティカル、ファンブルに合わせて修正が必要です。

2022-04-08 09:51 UTC, GenKuzumochi commented on lib/bcdice/game_system/CyberpunkRed.rb
> +      CP_RE = /^CP(?<ability>\d+)?(?<modifier>[+-]\d+)?(?<target>>=\d+)?/.freeze
定数が外部から参照できてしまうので、多分private_constantにする必要があります。
好みですが、定数の近くにコメントを書いておくのが意外と単純です。
```
dice.first == 10 # critical
```

2022-04-08 09:51 UTC, GenKuzumochi commented on lib/bcdice/game_system/CyberpunkRed.rb
> +        case command
cp_roll_resultやini_roll_resultの戻り地を、処理できなかった際はnilとすることで、全体が単純になります。
```
cp_roll_result(command) || ini_roll_result(command) || roll_table(command, TABLES)
```

2022-04-13 12:29 UTC, ysakasin requested changes
ありがとうございます。いくつかコードの指摘をしましたので、修正お願いします。

また、表についてですが、明らかな誤植がある２件は今回は追加せずに削除してください。誤植が修正され次第追加して欲しいです。

2022-04-13 12:29 UTC, ysakasin commented on lib/bcdice/game_system/CyberpunkRed.rb
> +        parser = Command::Parser.new('CP', round_type: RoundType::FLOOR).enable_suffix_number.enable_question_target
```suggestion
        parser = Command::Parser.new('CP', round_type: RoundType::FLOOR)
          .enable_suffix_number
          .restrict_cmp_op_to(nil, :>=)
```

`enable_question_target` を使うのは `>=?` のような記述を許容してしまうので、ふさわしくありません。
また、コマンドの使用を見る限り、比較演算子は `>=` のみ許容されるので、`restrict_cmp_op_to` で制限するのが良いです。

2022-04-13 12:29 UTC, ysakasin commented on lib/bcdice/game_system/CyberpunkRed.rb
> +        dices << @randomizer.roll_once(dice_face)
```suggestion
        dices = [@randomizer.roll_once(dice_face)]
```

2022-04-13 12:29 UTC, ysakasin commented on lib/bcdice/game_system/CyberpunkRed.rb
> +        result.text += ' ＞ '
```suggestion
        result.text = "(#{dice_cnt}D#{dice_face}#{Format.modifier(modify_number)}#{parsed.cmp_op}#{parsed.target_number})"
        result.text += ' ＞ '
        result.text += "#{dices.first}[#{dices.first}]#{Format.modifier(modify_number)}"
        result.text += ' ＞ '
```

2022-04-13 12:29 UTC, ysakasin commented on lib/bcdice/game_system/CyberpunkRed.rb
> +          result.text += ' ＞ 失敗！'
`!` はつけずに単に`成功`, `失敗`が良いと思います。

2022-04-13 12:29 UTC, ysakasin commented on lib/bcdice/game_system/CyberpunkRed.rb
> +        case command
@saronpasu このようにしてください。

2022-04-14 00:27 UTC, saronpasu commented
@ysakasin 指摘いただいた箇所を修正しました。確認お願いします。

2022-04-16 02:46 UTC, GenKuzumochi commented
INIコマンドは`1d10+反応`で行動値を決める的なものでしょうか？
特殊な処理がなければ、別途コマンドにする必要はなさそうです。

2022-04-16 14:24 UTC, saronpasu commented
@GenKuzumochi おっしゃる通り、`1d10+反応`を返すだけのものです。

2022-05-04 02:29 UTC, ysakasin approved these changes

2022-05-04 02:30 UTC, merged

2022-05-04 02:31 UTC, ysakasin commented
@saronpasu ありがとうございます！　マージしました。

@GenKuzumochi 🤝