[TorgEternity]高揚(UP)コマンドに修正値指定が出来るように拡張
bcdice/BCDice pull request #580
Opened 2022-11-08 03:50 UTC by Faceless192x

UPコマンドをUP[m]形式で記述できるように拡張しました。([m]は省略可)
現状のテストで、mの所に数式が入ると空文字列を返すように書かれていた為、数式には未対応としました。

2022-11-10 11:52 UTC, ysakasin requested changes

2022-11-10 11:52 UTC, ysakasin commented on lib/bcdice/game_system/TorgEternity.rb
> +        　　"UP[m]"で高揚状態のロール(通常の1d20に加え、1d20を追加で振り足し)を行います。
`[m]` が省略可能であることを書いた方がよさそうです。

2022-11-10 14:00 UTC, Faceless192x commented
ヘルプメッセージに「[m]が省略可能」である旨、記載しました。

2022-11-12 11:47 UTC, ysakasin approved these changes

2022-11-12 11:52 UTC, merged

2022-11-12 11:52 UTC, ysakasin commented
@Faceless192x ありがとうございます！　マージしました。