Hunter: The Reckoning 5th Editionダイスボット追加
bcdice/BCDice pull request #589
Opened 2022-11-27 13:45 UTC by FredGreenfield

## **【システム概要】**
「Hunter:the Reckoning 5th Edition」(Q2 2022, Renegade Game Studios)

- [Hunter: The Reckoning 5th Edition Roleplaying Game Core Rulebook](https://www.drivethrurpg.com/product/404271/Hunter-The-Reckoning-5th-Edition-Roleplaying-Game-Core-Rulebook)

World of Darkness 5th Edition世界のハンターをプレイするシステム。

###  **【コマンド概要】 **
　基本判定とハンターの特殊ダイスでの判定(Overreach,Despair)を実装した。Overreachが発生した場合はOverreachを続行するかDespairを選択するか選べるため、ユーザに選択肢を提示するようにした。

- 難易度指定あり：成功数のカウント、判定成功と失敗、Critical処理、Critical Winのチェックを行う。
                     （Desperationダイスがある場合）OverreachとDespairの発生チェックを行う。
- 難易度指定なし：成功数のカウント、判定失敗、Critical処理、（Desperationダイスがある場合）Despairチェックを行う。
                      判定成功、Overreachのチェックを行わない。
                      Critical Win、（Desperationダイスがある場合）Despair、Overreachのヒントを出力。
- Critical処理のみ、全てのチェックを行わない。

###  **【その他】 **
　既にリリースされている同様のシステムとして吸血鬼をプレイするVampire The Masquerade 5th Editionが存在し、基本的な判定ルールは共有している。また、恐らく同じように基本的な判定ルールを共有しているであろう人狼をプレイするWerewolf: The Apocalypse 5th Editionの発売が予定されている(2022/11/27現在)。
　今回のHunter: The Reckoning 5th EditionダイスボットはVampire The Masquerade 5th Editionのダイスボットとほぼ同じ処理を行っているが、継承や統合はせず、独立したダイスボットとした。

2022-11-27 22:39 UTC, FredGreenfield commented
たびたびご迷惑をおかけして申し訳ありません。

実際のプレイ時は頭のなかで無意識に算出していたので今の今まで抜けていたのですが、難易度指定時に成功の差分を表示した方が親切であることに気がつきました（V5も同様）。
判定の成功度合い、ダメージ算出、特殊能力の効果で使用するため、あった方がよいと考えています。
投稿後にこんな事を言うのも大概なのですが、後から追加するより、今、修正したいと考えています。

少々お待ちいただけると幸いです。

2022-12-03 02:29 UTC, ysakasin requested changes

2022-12-03 02:29 UTC, ysakasin commented on lib/bcdice/game_system/HunterTheReckoning5th.rb
> +        m = /\A(\d+)?(HRF)(\d+)(\+(\d+))?/.match(command)
```suggestion
        m = /\A(\d+)?(HRF)(\d+)(\+(\d+))?$/.match(command)
```
コマンドを正規表現でパースするときには、完全一致で動作するように記述してください。

2022-12-04 07:40 UTC, FredGreenfield commented on lib/bcdice/game_system/HunterTheReckoning5th.rb
> +        m = /\A(\d+)?(HRF)(\d+)(\+(\d+))?/.match(command)
ご指摘、ありがとうございます。修正いたします。
V:tM5thの方でも同じようになっていたので、近日中にそちらも修正いたします。

2022-12-15 13:56 UTC, ysakasin commented
@FredGreenfield 了解しました。レビューしても良い状態になったら、GitHub上で再度レビューリクエストを投げてください。

2022-12-19 12:57 UTC, ysakasin approved these changes

2022-12-19 12:58 UTC, merged