Feature/dnd5e
bcdice/BCDice pull request #594
Opened 2023-01-19 10:09 UTC by Faceless192x

「ダンジョンズ＆ドラゴンス第５版」をプレイしたところ、クリティカル・ファンブル・成功・失敗の表示が無く、BCdiceを使っているにしては「寂しい感じ」がしたので戦闘用ダイスコマンドを書いてみました。

実装コマンドは「AC」コマンドのみで、攻撃対象になった相手のACをnとして
ACnで実行します。
また、先頭に「+(有利)または-(不利)」を指定することで、有利不利のダイスを自動ロールします。
ex. +AC14 -AC18
とりあえずこれだけですが、戦闘が楽しくなれば幸いです。

2023-01-21 18:07 UTC, Faceless192x commented
うっかりダイスの修正値を指定する必要があるのを忘れていました。
また、チャットパレットに登録して使うことを考えると、コマンドのうち、訂正・入力の必要がある部分は固まっている方が良いのでACコマンドの書式を見直して変更しました。

・[x]AC[y]n
x:修正値
y:有利(P)、不利(N)
n:目標のアーマークラス

ex. AC15 ACP18 ACN14 +5AC16 -3ACP16

2023-01-25 23:19 UTC, ysakasin requested changes
ありがとうございます。いくつかフィードバックです。

## 式のフォーマット
加算ダイスに形式を寄せて、 `XXX+n>=t`の形式が良いと思います。

## 有利不利
英語では Advantage / Disadvantage なので、P / NでなくA / D が良いと思います。

## コマンド名
ACだとAbility Checksとも被ってしまうので、攻撃ロールであるとわかるようにAttack Rollsを省略して`AR`  `Attack` `AT` などにした方が良いと思います。

## ヘルプ
「命中判定」ではなく、日本語のルールブックに合わせて「攻撃ロール」と表記してください。

## 能力値判定について
攻撃ロールと違ってクリティカル/ファンブルがありませんが、有利不利を扱いやすくするために攻撃ロールと似たフォーマットでコマンドを用意してもいいかもしれません。こうしておくと、ヘルプにも書かれるので、能力値判定で攻撃ロールコマンドを使ってしまうような問題が緩和されると思います。

2023-01-25 23:50 UTC, Faceless192x commented
> ### 式のフォーマット
>
>加算ダイスに形式を寄せて、 XXX+n>=tの形式が良いと思います。

2023-01-26 00:01 UTC, Faceless192x commented
早速のフィードバックありがとうございます。

> ## 式のフォーマット
> 
> 加算ダイスに形式を寄せて、 `XXX+n>=t`の形式が良いと思います。

　ここが悩ましいところですね。

・加算ダイスに形式を合わせた方がコマンドとして覚えがよく、混乱しにくい

のと

・加算ダイスでは必要であったが、専用ダイスコマンドでは自明な指定はできるだけ排除したい
・デファクトスタンダードであるキャラクターシートが、判定用コマンドを自動出力する都合上、書き換えの手間をなるべく省きたい
・セパレータとしてみたときに「>=」と二文字になるのは不格好である

　の両方を満たせるコマンドが理想なのですが、なかなかそうもいかず。

　コマンドの読み替えは前例がありますので、複数フォーマットから同一機能を使えるようにしてはどうかと思うのですが、どうでしょう？


　これ以外は、まったくもっておっしゃる通りですね。(^^;

2023-01-26 00:35 UTC, ysakasin commented
> 専用ダイスコマンドでは自明な指定はできるだけ排除したい

これについては読みと書きのトレードオフだと考えています。前提知識が自明な指定がある方が読み優先となり、コマンドの意味が理解しやすいので、私は自明な指定を推奨しています。

> 書き換えの手間をなるべく省きたい

`XXXA+x>=t`は、有利不利の位置とACの位置が離れているという点が問題かと思います。`XXX+x>=tA`のように末尾に指定する方式を採用してもいいと思います。例えば `Cthulhu7th` で技能判定の難易度ハードは `CC<=75h` の形式です。こうするとチャットパレットは `XXX+x>=` としておくことができます。

> セパレータとしてみたときに「>=」と二文字になるのは不格好である

`>=` の代わりに `AC` にして、`AR+xACt` などするのも一興かもしれません。こうすればACとして`t`指定しているのは自明ですし、不格好さは緩和されるかと思います。ただ、私としては `>=` を推奨したいです。

> コマンドの読み替えは前例がありますので、複数フォーマットから同一機能を使えるようにしてはどうかと思うのですが、どうでしょう？

方向性が読み解けなかったので、具体例を交えて提案いただけると助かります。

2023-01-26 01:16 UTC, Faceless192x commented
> > 書き換えの手間をなるべく省きたい
> 
> `XXXA+x>=t`は、有利不利の位置とACの位置が離れているという点が問題かと思います。`XXX+x>=tA`のように末尾に指定する方式を採用してもいいと思います。例えば `Cthulhu7th` で技能判定の難易度ハードは `CC<=75h` の形式です。こうするとチャットパレットは `XXX+x>=` としておくことができます。

　ああ！これは良いですね！
　この方向で修正します。

2023-02-17 13:53 UTC, ysakasin requested changes
能力値判定のテストケースがないようなので、追加をお願いします。

2023-02-17 22:34 UTC, Faceless192x commented
失礼しました。うっかり放置状態になっておりました。
能力値判定のテストケースを追加しましたので、お手隙の時にご確認お願いします。

2023-02-18 08:42 UTC, ysakasin approved these changes

2023-02-18 08:42 UTC, merged

2023-02-18 08:42 UTC, ysakasin commented
ありがとうございます！　マージしました。