シノビガミ：記述の更新／旧記述の別コマンド化（改訂版準拠）、新要素の追加、異形表の挙動の更新、ヘルプの更新
bcdice/BCDice pull request #608
Opened 2023-03-05 13:49 UTC by NiSLa-NiSlimeTRPG

・記述の更新／旧記述の別コマンド化（改訂版準拠）
　WT,BTについて改訂版の記述に準拠したものに更新しました。旧文庫版の記述はOWT,OBTとして残してあります。
　GWTについても改訂版の記述に更新しました。

・新要素の追加
`　新戦場表 BNT、【数奇】OTS、妖術変調対応表（現代／戦国）YWT、妖魔化（新異形表利用） NMT、新異形表 NMTR、妖魔忍法表（x:1-異霊 2-凶身 3-神化 4-攻激）DSNx`
　ヘルプにもある通りこれらを追加しました。

・異形表の挙動の更新
　三木里さんの提供してくださったコードに基づき異形表の挙動の更新を行いました。それに伴い、`MTR`で異形表単体、`DSx （x：A,B,C）`で妖魔忍法表単体で振れる仕様になりました。

・ヘルプの更新
　以上の変更への対応をするとともに、ヘルプを更新しました。

2023-03-05 14:01 UTC, NiSLa-NiSlimeTRPG commented
最後の`cop.diff patched`のCommitでお願いします！！
Commitばかりで申し訳ない！

2023-03-17 18:50 UTC, ysakasin requested changes

2023-03-17 18:50 UTC, ysakasin commented on test/data/ShinobiGami.toml
> +output = '新異形表(2) ＞ 妖魔忍法表・凶身(5) ＞ 凶身態。「妖魔忍法表・凶身」を使用し、妖魔化している間、その妖魔忍法を修得する。 ＞ 【百眼】(基本 p173)／【鬼胎】（隠忍 p29）'
処理の流れからして、 

```
'新異形表(2) ＞ 凶身態。「妖魔忍法表・凶身」を使用し、妖魔化している間、その妖魔忍法を修得する。 ＞ 妖魔忍法表・凶身(5) ＞ 【百眼】(基本 p173)／【鬼胎】（隠忍 p29）'
```

であるべきなので、この順番に表示されるように動作を変更してください。

2023-03-25 11:10 UTC, ysakasin approved these changes

2023-03-25 11:11 UTC, merged

2023-03-25 11:14 UTC, ysakasin commented
@NiSLa-NiSlimeTRPG @hetaregirl1802 @h-mikisato ありがとうございます。マージしました。