ダンジョンズ＆ドラゴンス第５版、武器の両手持ちのダメージに対応
bcdice/BCDice pull request #612
Opened 2023-03-20 05:01 UTC by Faceless192x

D&Dの第５版、パラディンとファイターが武器を両手持ちした時のダメージのリロールに対応するコマンドを実装してみました。

・両手持ちのダメージ　2HnDx[m]
        　n:ダイスの個数
        　x:ダイスの面数
        　m:+-修正。省略可。
        　パラディンとファイターの武器の両手持ちによるダメージダイスの1,2の出目の振り直しを行います。

判り易く、通常のダイスコマンド(Dコマンド)に2Hを頭に足せば両手持ちになります。

ご確認の後、問題なければ取り込みをお願いします。

2023-03-22 02:43 UTC, ysakasin requested changes

2023-03-22 02:43 UTC, ysakasin commented on lib/bcdice/game_system/DungeonsAndDragons5.rb
> +        if new_dice.!empty?
```suggestion
        if new_dice.empty?
```
記述ミスかと思いますので修正お願いします

2023-03-22 03:01 UTC, Faceless192x commented on lib/bcdice/game_system/DungeonsAndDragons5.rb
> +        if new_dice.!empty?
if じゃなくて unless を使った方が良いということでしょうか？
実は素では「if new_dice.length > 0」と書いていたらrubocop先生に「そこは .!empty? だろ」と訂正されたのでしたｗ

2023-03-22 03:31 UTC, ysakasin commented on lib/bcdice/game_system/DungeonsAndDragons5.rb
> +        if new_dice.!empty?
いえ、単に文法上 `.!empty?` という記法がないです。そのためテストも全て失敗しています。 

`if !new_dice.empty?`が正しかったんですね。 `unless` と `if !` のどちらでも問題ないです、

2023-03-22 03:43 UTC, Faceless192x commented on lib/bcdice/game_system/DungeonsAndDragons5.rb
> +        if new_dice.!empty?
なんと！私の環境ではテストを通ってました。(流石の私も、テストしないでPull Requestは送れないですからね)
文法上存在しないものがrubocopから提示されるとは考えてもみなかったですね。
そういうこともあるんだなぁ。

2023-03-23 00:15 UTC, Faceless192x commented
先日D&D5edをプレイしていて、ファイターの類型などによって武器攻撃時のクリティカル値が変動することを知りました。
慌ててATコマンドをクリティカル値を指定出来るように改修しました。

        ・攻撃ロール　AT[x][@c][>=t][y]
        　x：+-修正。省略可。
        　c:クリティカル値。省略可。
        　t:敵のアーマークラス。>=を含めて省略可。
        　y:有利(A), 不利(D)。省略可。
        　ファンブル／失敗／成功／クリティカル を自動判定。

内容をご確認ください。

2023-03-25 11:12 UTC, ysakasin approved these changes

2023-03-25 11:12 UTC, merged

2023-03-25 11:14 UTC, ysakasin commented
@Faceless192x ありがとうございます。マージしました。

両手持ちコマンドの追加と攻撃ロールのクリティカルの件は、それぞれ独立して議論できることだと思います。次回このようなケースがあれば別々のPull Requestにしていただけると助かります。

2023-03-25 12:10 UTC, Faceless192x commented
了解しました。
以後気をつけます。