RuneQuest:Roleplaying in Gloranthaのダイスボット作成
bcdice/BCDice pull request #637
Opened 2023-08-05 14:13 UTC by FredGreenfield

# １．背景
　ルーンクエストの新版であるRuneQuest: Roleplaying in Glorantha(以下、RQG)日本語版の2023年秋発売を受け、当該システムのダイスボットを作成する。
　https://ci-en.net/creator/11464/article/798357
　先行して「ルーンクエスト」ダイスボットが存在するが、このダイスボットは旧システムを対象にしており、非推奨のxDyの動作を修正するスタイルとなっていることから、RQG用に新規作成するものとする。
***
# ２．方針
- 　用語について
　　日本語版が発売されていないため、用語はクイックスタート日本語版を参照する。
　　https://www.chaosium.com/runequest-roleplaying-in-glorantha-quickstart/
　　RQG日本語版が発売されたときに、採用した用語と異なる場合は可能な限り速やかに修正を行う事とする。
- 　コマンド書式について
　　同種の処理はクトゥルフ神話TRPGダイスボットの書式を参考にする。
***
# ３．ダイスボット名
　日本語版ユーザが発見しやすく、馴染みやすいようにカタカナ日本語の「ルーンクエスト：ロールプレイング イン グローランサ」とする。「２．方針」の用語ルールに従い、RQG日本語版発売後に異なる名称だった時は変更を行う。
　RQGはケイオシアム社公式で4版となっているため、命名ルールに従った読み仮名は「るうんくえすと4」とする。今後、RuneQuestの4版と呼ばれる別システムが出版され、ダイスボットを作成する際は、新たに作成されるダイスボットの方で対応されたい。
***
# ４．コマンド
- 　技能判定コマンド
　　RQG<=xx
　　⇒ 結果表示例：RQG<=55
　　(1D100<=55) ＞ 01 ＞ クリティカル/スペシャル
　　(1D100<=55) ＞ 11 ＞ スペシャル
　　(1D100<=55) ＞ 55 ＞ 成功
　　(1D100<=55) ＞ 89 ＞ 失敗
　　(1D100<=55) ＞ 00 ＞ ファンブル

　上記のコマンドで1d100の結果を技能値(xx)と比較、判定する。
　結果はクリティカル(1あるいは技能の1/20以下)、スペシャル(技能の1/5以下)、成功(01-05あるいは技能以下)、失敗(96-00あるいは、技能を上回る)、ファンブル(00あるいは00-失敗確率の1/20以上)の５種類。各計算はRQGルールブック p143,Ability Results Tableの通りとなる。端数は四捨五入。
　ただし、技能値0はStarter Set,Book1,p5において成功確率がないと記述されているため、xxに0が指定された場合は必ず失敗の判定を返す。

　　RQG
　　⇒ 結果表示例：RQG
　　(1D100) ＞ 19

　クトゥルフ神話TRPGダイスボットと同じように1d100のエイリアスとして機能する。

- 　抵抗判定コマンド
　　抵抗判定（RESistance roll）RQG, p145
　　RES(x-y)Mz
　　⇒ 結果表示例：RES(10-10)M5
　　(1D100<=55) ＞ 01 ＞ クリティカル/スペシャル
　　(1D100<=55) ＞ 11 ＞ スペシャル
　　(1D100<=55) ＞ 55 ＞ 成功
　　(1D100<=55) ＞ 89 ＞ 失敗
　　(1D100<=55) ＞ 00 ＞ ファンブル

　クトゥルフ神話TRPGと同じ書式の上記のコマンドで、能力値xで対抗する能力値yとの差分x5%+50%を1d100判定を行う（参考：RQG Resistance Table p147）。判定の結果は、RQGコマンドと同じとする。xのみを指定した場合は差分計算後として処理する。zは省略可能で、増強などにより直接成功率に影響する修正(%単位)を指定する(参考：RQG p146)。

- 　能動側抵抗判定コマンド（ReSistance Active characteristic roll）RQG, p145
　　RSAxMz
　　⇒ 結果表示例：RSA(10)M5
　　(1D100<=55) ＞ 01 ＞ 成功
       クリティカル/スペシャル、ファンブルは未処理。必要なら確認すること。
　　(1D100<=55) ＞ 02 ＞ 成功
       クリティカル/スペシャル、ファンブルは未処理。必要なら確認すること。
　　(1D100<=55) ＞ 55 ＞ 成功 ＞ 相手側能力値10まで成功
       クリティカル/スペシャル、ファンブルは未処理。必要なら確認すること。
　　(1D100<=55) ＞ 99 ＞ 失敗
       クリティカル/スペシャル、ファンブルは未処理。必要なら確認すること。
　　(1D100<=55) ＞ 00 ＞ 失敗
       クリティカル/スペシャル、ファンブルは未処理。必要なら確認すること。

　クトゥルフ神話TRPGには無いコマンド。受動側の能力値が不明の時などのために、能動側の能力値のみで判定し、いくつの受動側能力値まで成功できるかを表示する。判定の結果にはクリティカル/スペシャル、ファンブルは判定しない。zは省略可能で、増強などにより直接成功率に影響する修正(%単位)を指定する(参考：RQG p146)。
　判定結果は対抗相手の能力に対してどの値まで成功なのかを表記する。ただし、01-05は無条件成功、96-00は無条件失敗となる。

2023-08-05 15:19 UTC, ysakasin requested changes

2023-08-05 15:19 UTC, ysakasin commented on lib/bcdice/game_system/RuneQuestRoleplayingInGlorantha.rb
> +        funmble_value = ((100 - success_value.to_f) / 20).round
切り捨て `floor` ではなく、四捨五入 `round` ということで間違いないでしょうか？

2023-08-05 15:19 UTC, ysakasin commented on lib/bcdice/game_system/RuneQuestRoleplayingInGlorantha.rb
> +        ability_value = Arithmetic.eval(m[3], :round)
`:round` でなく `RoundType::ROUND` を用いてください。もしくは、 `#initialize` で `@round_type` を設定しておいて、 `@round_type` を参照するようにしてください。

2023-08-05 15:19 UTC, ysakasin commented on lib/bcdice/game_system/RuneQuestRoleplayingInGlorantha.rb
> +        Result.nothing
`Result.nothing` が返されると汎用コマンドが動作しなくなってしまうので、 `nil` を返すようにしてください。 `Result.nothing` は基本的に`Base#result_2d6` などで使われることを想定しているので、専用コマンドでは使わないほうが良いです。

2023-08-05 21:37 UTC, FredGreenfield commented on lib/bcdice/game_system/RuneQuestRoleplayingInGlorantha.rb
> +        funmble_value = ((100 - success_value.to_f) / 20).round
はい、四捨五入です。

例えば、ルールブックp143のAbility Results Tableから一部抜粋すると、以下のようになっております。

| 成功率 | CR(1/20) | SP(1/5) | FB(1/20) |
| ---- | ---- | ---- | ---- | 
|68-69| 1-3 | 1-14 | 99-00 |    
|   70  | 1-4 | 1-14 | 99-00 |                                 
|71-72| 1-4 | 1-14 | 00 |                                 
|73-77| 1-4 | 1-15 | 00 |

2023-08-05 21:38 UTC, FredGreenfield commented on lib/bcdice/game_system/RuneQuestRoleplayingInGlorantha.rb
> +        ability_value = Arithmetic.eval(m[3], :round)
了解しました。

2023-08-05 21:38 UTC, FredGreenfield commented on lib/bcdice/game_system/RuneQuestRoleplayingInGlorantha.rb
> +        Result.nothing
こちらも了解しました。

2023-08-06 09:18 UTC, ysakasin approved these changes

2023-08-06 09:18 UTC, merged

2023-08-06 09:18 UTC, ysakasin commented
@FredGreenfield ありがとうございます！　マージしました。