『砂塵戦機アーガス 2nd Edition』のダイスを作成しました
bcdice/BCDice pull request #641
Opened 2023-09-02 12:57 UTC by Faceless192x

『砂塵戦機アーガス 2nd Edition』の専用ダイスの要望がありましたので、『砂塵戦機アーガス』のダイスを継承して2nd Ed.用のダイスを作成してみました。
　rubocop通過済みです。

        ・一般判定Lv（チャンス出目0→判定0） nAG+x
        　　　nは習得レベル、Lv0の場合nの省略可能。xは判定値修正（数式による修正可）、省略した場合はレベル修正0
        　　　例）AG:習得レベル0の一般技能、1AG+1:習得レベル1・判定値修正+1の技能、AG+2-1：習得レベル0・判定値修正2-1の技能、(1-1)AG：習得レベル1・レベル修正-1の技能

        ・適正距離での命中判定（チャンス出目0→判定0、HR算出）OM+y@z
        　　　yは命中補正値（数式可）、zはクリティカル値。クリティカル値省略時は0
        　　　HRの算出時には、HRが大きくなる場合に出目0を10に読み替えます。
        　　　例）OM+18-6@2:命中補正値+18-6でクリティカル値2、適正距離の判定

        ・非適正距離での命中判定（チャンス出目0→判定0、HR算出）NM+y@z
        　　　yは命中補正値（数式可）、zはクリティカル値。クリティカル値省略時は0
        　　　HRの算出時には、HRが大きくなる場合に出目0を10に読み替えます。
        　　　例）NM+4-3:命中補正値+4-3で非適正距離の判定

        ・クリティカル表　　 CR
        ・鹵獲結果表　　　　 CAP
        ・幕間クエスト表　　 INT
        ・サルベージ表　　　 SAL
        ・赤字ペナルティー表 DEF
        ・特殊戦況表　　　　 SPE

        ※通常の1D10などの10面ダイスにおいて出目10の読み替えはしません。コマンドのみです。
        　ページ参照は、何もない場合は「ルールブック」、wは「西風旅徨」を示します。

　と、実際には「鹵獲結果表」以下の表を追加しただけになります。

　このシステムはd10の扱いが所謂d9スタイルなのですが、表を作成していて「DiceTable::Table」や「DiceTable::RangeTable」がd9を想定していないことに気が付きました。(0では開始できない。0..1なら実行可能)
　優先度は低いですが、頭に入れておくと良いかもしれませんね。

　ともあれ、必要そうな表の実装が出来ましたのでpull requestを送ります。
　お手隙の際にご確認ください。

2023-09-02 17:13 UTC, ysakasin requested changes

2023-09-02 17:13 UTC, ysakasin commented on lib/bcdice/game_system/SajinsenkiAGuS2E.rb
> +      end
```suggestion
      def eval_game_system_specific_command(command)
        super(command) ||
          roll_tables(command, SECOND_ED_TABLES)
      end
```

オーバーライド前のメソッドを呼び出す `super` を使うのが良いかと思います。

2023-09-02 17:13 UTC, ysakasin commented on lib/bcdice/game_system/SajinsenkiAGuS2E.rb
> +        ),
DiceTable系はいわゆる D9 をサポートしていないので、`2D9`だと本当に9面ダイスが2個振られてそれぞれ1〜9の目が出ることになってしまいます。

テストケースに `value = 0` と書ける上に動作してしまうので、誤解させてすみません。

`RangeTable` を継承するなどして動作を調整してもらうのが良いと思います。

2023-09-02 17:13 UTC, ysakasin commented on lib/bcdice/game_system/SajinsenkiAGuS2E.rb
> +      register_prefix('-?\d*AG', 'OM', 'NM', TABLES.keys, SECOND_ED_TABLES.keys)
```suggestion
      register_prefix_from_super_class()
      register_prefix(SECOND_ED_TABLES.keys)
```

親クラスのprefixを引き継げる [`BCDice::Base.register_prefix_from_super_class`](https://github.com/bcdice/BCDice/blob/825b39928a708afd1fd5e33a62a5a1bf70ba0450/lib/bcdice/base.rb#L27-L29) を使うのが良さそうです。

2023-09-03 00:00 UTC, Faceless192x commented on lib/bcdice/game_system/SajinsenkiAGuS2E.rb
> +      end
そうでした！スッキリしますね。修正します。

2023-09-03 00:02 UTC, Faceless192x commented on lib/bcdice/game_system/SajinsenkiAGuS2E.rb
> +        ),
とりあえず、今の所ガンドックとアーガスくらいなので姑息な手段で済ませることにしました。
将来的にはサポートされると良いですね。

2023-09-03 00:02 UTC, Faceless192x commented on lib/bcdice/game_system/SajinsenkiAGuS2E.rb
> +      register_prefix('-?\d*AG', 'OM', 'NM', TABLES.keys, SECOND_ED_TABLES.keys)
ありがとうございます。こちらも修正します。

2023-09-03 00:04 UTC, Faceless192x commented
今までご指摘があった修正を行いました。
お手隙の時に、ご確認ください。

2023-09-03 03:37 UTC, ysakasin approved these changes

2023-09-03 03:38 UTC, merged

2023-09-03 03:38 UTC, ysakasin commented
@Faceless192x ありがとうございます。マージしました！