[神聖課金RPGディヴァインチャージャー]専用ダイスを作成しました
bcdice/BCDice pull request #677
Opened 2024-02-09 04:45 UTC by Faceless192x

『神聖課金RPGディヴァインチャージャー( https://r-r.arclight.co.jp/rpg/skdc/ )』用のダイスを作成しました。
　「判定」、「反転時の判定」、各種表のうち頻出しそうな「ランダムイベント」「神器」のふたつを実装してみました。
　コマンドは以下の通りです。

        ■判定　　nD6>=t          n:能力値 t:目標値
        　もしくはnD>=t
        例)3D6>=7: ダイスを3個振って、目標値7で判定。その結果(達成値,成功・失敗,クリティカル,ファンブル)を表示
        　 3D6>=?: 　同上　目標値が不明なので、達成値,クリティカル,ファンブルのみ表示。

        ■反転判定　　REV[n]>=t   n:ダイス目(カンマなし) t:目標値
        例)REV[123]>=7: 振ったダイスが[1,2,3]で、目標値7で反転判定。その結果(達成値,成功・失敗,クリティカル,ファンブル)を表示

        ■ランダムイベント　　RET
        ■神器　　　　　　　　aksT a:表(AかB) k:種別(K:近接, S:射撃, M:魔法, Y:鎧, T:盾, A:装飾品) s:ランク(1～5)

お手隙の際に、ご確認くださいませ。

2024-02-13 09:40 UTC, ysakasin approved these changes
Pull Requestありがとうございます。

`nD6>=t` ですが、これは汎用コマンドのフォーマットと同一にせずに、別形式にするようにしてください。`D`の部分をDivineChargerの頭文字をとって`DC`変えるなどです。

2024-02-13 09:40 UTC, ysakasin requested changes
Pull Requestありがとうございます。

nD6>=t ですが、これは汎用コマンドのフォーマットと同一にせずに、別形式にするようにしてください。Dの部分をDivineChargerの頭文字をとってDC変えるなどです。

2024-02-13 23:20 UTC, Faceless192x commented
お疲れ様です。
判定コマンドを「D6」から「DC」に変更しましたので、ご確認ください。

2024-02-25 22:11 UTC, merged

2024-02-25 22:11 UTC, ysakasin commented
@Faceless192x ありがとうございます。マージしました。

2024-02-25 23:32 UTC, Faceless192x commented
ありがとうございます！