[フルフェイス] (UPDATE) 一般判定の成否と戦闘判定のダメージ計算を実装しました
bcdice/BCDice pull request #679
Opened 2024-02-16 04:59 UTC by Faceless192x

フルフェイス( https://booth.pm/ja/items/5302609 )のダイスに「6の目の数」「成否」と「ダメ―ジ計算」を入れて欲しいと要望があったので追加しました。

        ■判定　x+bFF<=[a[,t]]d   x:ヒート(省略時は3) b:判定修正 a:能力値 t:難易度(省略可) d:基本ダメージ(省略可)

        例)FF<=[2]:   能力値2で判定し、その結果(成功数,1の目の数,6の目の数,バースト)を表示。
           6FF<=[3]:  ヒート6,能力値3で戦闘判定し、その結果( 〃 )を表示。
           8+2FF<=[3]:ヒート8,判定修正+2,能力値3で戦闘判定し、その結果( 〃 )を表示。
           FF<=[2,1]: 能力値2,難易度1で判定し、その結果(成功数,1の目の数,6の目の数,成功・失敗,バースト)を表示。
           6FF<=[3]1:  ヒート6,能力値3で戦闘判定し、その結果(成功数,1の目の数,6の目の数,ダメージ,バースト)を表示。

と若干コマンドの説明がうるさくなりました。

お手隙の際に、ご確認ください。

2024-02-17 11:50 UTC, ysakasin requested changes
Pull Requestありがとうございます。

`FF` コマンドの互換性がなくなってしまったので、互換性のある形式に変更してください。互換性のない変更が許容できるのは、以前の形式がゲームシステムのルールに則っていないなど、バグを修正する場合のみです。

2024-02-17 12:39 UTC, Faceless192x commented
了解しました。
FFコマンドの動作を元に戻して、新機能はFAコマンドとFBコマンドに分けて新設しました。

2024-02-23 00:07 UTC, Faceless192x commented
・FFコマンドを後方互換を維持する方向で決定しました。
・ダイスロールの結果をソートするようにして、結果を確認しやすくしました。

以上、お手隙の際にご確認ください。

2024-02-25 21:45 UTC, ysakasin approved these changes

2024-02-25 21:45 UTC, merged

2024-02-25 21:45 UTC, ysakasin commented
@Faceless192x ありがとうございます。マージしました。

2024-02-25 23:33 UTC, Faceless192x commented
ありがとうございます！