[Arknights Fan TRPG] アップデート
bcdice/BCDice pull request #700
Opened 2024-05-06 06:04 UTC by Ayase00

・成功、失敗とクリティカル、エラーの優先度をルール準拠に変更。
・ヘルプメッセージの誤りを修正。
・ココフォリアのルーム変数に対応するため、役職名の後ろに0がつくと動作せず、1がつくと動作するように整備。

2024-05-09 09:49 UTC, ysakasin requested changes
古いコミットが残ってしまっているので、コミットを整理するようお願いします

2024-05-16 11:18 UTC, Ayase00 commented
対応遅れてしまい申し訳ありません。
コミット整理承知いたしました。
Pull request の前にフォーク元(BcDice本体)の変更をマージして取り込んでおく処理は止めておいたほうが良いでしょうか？

2024-05-16 13:08 UTC, raa0121 commented
こちらですが、前回の Arknights Fan TRPG の取り込みが、squash merge となっており、コミットがまとめられてます。#666 f1db21f2e26739e2e8ae8c442434f92d9b65234b
なので、手元とBCDice 本体のツリー情報に差分があり、過去のコミットがこのPRに混じっているという状況になっています。
したがって、BCDice の master から新しくブランチを切り直して、そこに今回の差分を乗せるという形が良いと思います。
こちらの方針については、Arknights Fan TRPG のコードの共同開発者の @NOBUTOKA さんにもDiscord で伝えてあります。
よろしくお願いします。

2024-05-16 13:16 UTC, Ayase00 commented
ありがとうございます。discordの方確認致しました。２度お手間をおかけする形となってしまい申し訳ありませんでした。
対応したく思いますので、少々お時間頂けますと幸いです。

2024-08-11 13:15 UTC, closed without merging