TRPG『慈悲なきアイオニア』のダイスボット
bcdice/BCDice pull request #720
Opened 2024-06-04 10:18 UTC by hattarhaptag

慈悲なきアイオニアのダイスボットを作成しました。
技能判定の際に使うダイスボットで、ダメージチェックやストレスチェック、表などは作成していません。
作成したテスト(Aionia.toml)をすべてpassしています。
そのほか、ソートキー等のテストも通過しています。

2024-06-23 06:55 UTC, ysakasin requested changes
1文字コマンドは共通コマンドのために開けておきたいので、技能判定の`s`は形式を変更してください。コマンドの主要部分は2文字以上であることが望ましいです。

また、既存のコマンドの先頭に`s`をつけると[シークレットダイス](https://docs.bcdice.org/secret.html)になる機能があるため、形式を変更する際には気をつけてください。たとえば、`ST`と`SST`というコマンドを実装した場合に`SST`と入力した際に`ST`のシークレットダイスなのか、`SST`というコマンドなのか区別ができなくなります。

2024-06-25 04:38 UTC, hattarhaptag commented
@ysakasin 
コメントいただきありがとうございます。
技能をSkillと訳しS(ST)としていましたが、Abilityと解釈してAB(ABT)のようにコマンドを修正しました。
お手数をおかけしますがご確認よろしくお願いいたします。

2024-06-26 10:37 UTC, ysakasin requested changes

2024-06-26 10:37 UTC, ysakasin commented on lib/bcdice/game_system/Aionia.rb
> +        return "(#{command}) ＞ #{dice_total}[#{dice_list.join(',')}]#{bonus_text} ＞ #{bonus_result}#{result}"
成否やクリティカル・ファンブルの結果を伴う出力には [`BCDice::Result`](https://yard.bcdice.org/BCDice/Result.html) クラスのインスタンスを用いるようにしてください。

以下が使用例です。
https://github.com/bcdice/BCDice/blob/48a94e09701b5f5e11604b0c33d93db10ddcd388/lib/bcdice/game_system/Ayabito.rb#L84-L90

2024-07-01 06:36 UTC, hattarhaptag commented
@ysakasin
コメントいただきありがとうございます。
Resultクラスを用いて判定を返すようにプログラムを修正しました。
また、その変更に伴いテストデータにもsuccess, failure, critical, fumble情報を追加しました。
テストが100%パスしていることを確認しましたので、メンションする形でご連絡いたします。
ご確認よろしくお願いいたします。

2025-01-30 15:15 UTC, ysakasin approved these changes

2025-01-30 15:15 UTC, merged