『キズナバレット』の追加
bcdice/BCDice pull request #722
Opened 2024-06-20 22:39 UTC by satsumawagashi

『キズナバレット』のダイスボットを作成しました。
『第1巻』と『第2巻』（つまり現在刊行されている全巻）に掲載されている、作戦判定（カスタマイズしても6面指定しか省略できない）以外のすべての判定と、セッション中に振るすべての表を実装しています。
作成したテスト(KizunaBullet.toml)とrubocopをすべてpassしています。

2024-06-23 07:03 UTC, ysakasin requested changes
`nDS`コマンドですが、 `nD6` と比較しても入力内容においても動作においても改善される点がないため、`nDS`は削除してください。

2024-06-23 23:45 UTC, satsumawagashi commented
レビューしていただきありがとうございます。
nDS コマンドを削除しました。

2024-06-24 11:32 UTC, ysakasin approved these changes

2024-06-24 11:33 UTC, merged

2024-06-24 11:34 UTC, ysakasin commented
@satsumawagashi
Pull Requestありがとうございます。マージしました。

ブランチ名に日本語を使うとGitHub上で警告文が表示されてしまうため、次回以降Pull Requestを下さる際にはブランチ名には英数記号のみを使っていただけると助かります。