『トレイル・オブ・クトゥルー』専用ダイスを作成しました
bcdice/BCDice pull request #728
Opened 2024-06-25 18:31 UTC by Faceless192x

『トレイル・オブ・クトゥルー』( https://www.groupsne.co.jp/products/ToC/index.html )の専用ダイスを作成しました。
今度は中身が入っています。

        ■技能判定　TCb[>=t]   b:消費プール・ポイント t:難易度(省略可能)

        例)TC2>=5:消費プール・ポイント2,難易度5で技能判定し、その結果を表示する。
           TC>=3: 難易度3で技能判定し、その結果を表示する。
           TC:    難易度指定せずに技能判定する。
           TC3:   消費プール・ポイント3,難易度指定せずに技能判定する。

        ■神話的狂気表　MMT[a,b]   a,b:除外する神話的狂気(省略時は全神話的狂気を表示する)

        例)MMT[1,8]: 神話的狂気のうち、1番と8番を除外してロールし、神話的狂気を決定する。
           MMT2,6:   神話的狂気のうち、2番と6番を除外してロールし、神話的狂気を決定する。
           MMT:      神話的狂気を1番から8番まで列挙する。

以上の二つのコマンドを実装しました。rubocop通過済み。

お手隙の際にご確認ください。

2024-06-26 10:48 UTC, ysakasin requested changes

2024-06-26 11:54 UTC, Faceless192x commented on lib/bcdice/game_system/TrailOfCthulhu.rb
> +        bonus = ArithmeticEvaluator.eval(m[1])
1. 空文字の場合も「消費プール・ポイントが0である」という処理を行うために、ArithmeticEvaluator.eval()を使いましたが、nilの場合は0という処理を行った方が良いということでよろしいですか？
2. 「不正な式」ではなく、ToCでは「純粋主義モード」の場合は、難易度がKPから指定されずに技能判定を行う必要があるので、難易度がなくてもロールできるようにしています。

2024-06-26 11:54 UTC, Faceless192x commented on lib/bcdice/game_system/TrailOfCthulhu.rb
> +        m = /^MMT(\[?([,\d]+)\]?)?/.match(command)
了解しました！
そのように修正します。

2024-06-26 12:14 UTC, Faceless192x commented on lib/bcdice/game_system/TrailOfCthulhu.rb
> +        bonus = ArithmeticEvaluator.eval(m[1])
了解しました！
式の内容を見て、不正式の場合はnilを返すようにしてみます。

2024-06-27 11:09 UTC, ysakasin approved these changes

2024-06-27 11:09 UTC, merged

2024-06-27 11:10 UTC, ysakasin commented
@Faceless192x 
ありがとうございます！　マージしました

2024-06-27 11:49 UTC, Faceless192x commented
ありがとうございます！