[DoubleCross]ハプニングチャートの振るためのコマンド(HC)を追加
bcdice/BCDice pull request #736
Opened 2024-08-21 14:08 UTC by RYOSKATE

『DoubleCorss』に、フォーカスシステム(FS)判定用のハプニングチャートが欲しく実装を試みました。

- [x] [Pull Requestを送る前に確認したいこと](https://github.com/bcdice/BCDice/wiki/Pull-Request%E3%82%92%E9%80%81%E3%82%8B%E5%89%8D%E3%81%AB%E7%A2%BA%E8%AA%8D%E3%81%97%E3%81%9F%E3%81%84%E3%81%93%E3%81%A8)
```bash
~/ghq/github.com/bcdice/BCDice$ bundle exec rubocop -a
Inspecting 400 files
................................................................................................................................................................................................................................................................................................................................................................................................................

400 files inspected, no offenses detected

Tip: Based on detected gems, the following RuboCop extension libraries might be helpful:
  * rubocop-rake (https://rubygems.org/gems/rubocop-rake)

You can opt out of this message by adding the following to your config (see https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
  AllCops:
    SuggestExtensions: false
```
```bash
~/ghq/github.com/bcdice/BCDice$ bundle exec rake test
Loaded suite /home/ryoskate/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rake-13.1.0/lib/rake/rake_test_loader
Started
Finished in 51.36861476 seconds.
-------------------------------------------------------------------------------------------------------------------
18111 tests, 117945 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-------------------------------------------------------------------------------------------------------------------
352.57 tests/s, 2296.05 assertions/s
Warning: coverage data provided by Coverage [421] exceeds number of lines in /home/ishizue/ghq/github.com/bcdice/BCDice/lib/bcdice/game_system/DoubleCross.rb [420]
Coverage report generated for fork-22356 to /home/ishizue/ghq/github.com/bcdice/BCDice/coverage. 21994 / 22883 LOC (96.12%) covered.
Running RuboCop...
Inspecting 400 files
................................................................................................................................................................................................................................................................................................................................................................................................................

400 files inspected, no offenses detected

Tip: Based on detected gems, the following RuboCop extension libraries might be helpful:
  * rubocop-rake (https://rubygems.org/gems/rubocop-rake)

You can opt out of this message by adding the following to your config (see https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
  AllCops:
    SuggestExtensions: false
```

2024-12-28 05:31 UTC, patchang86 commented on lib/bcdice/game_system/DoubleCross.rb
> +
```suggestion
・RWプロローグチャート（PC）

2024-12-28 05:35 UTC, patchang86 commented on lib/bcdice/game_system/DoubleCross.rb
```suggestion
・register_prefix('\d+DX', 'PCP')
・register_prefix('\d+DX', 'PCN')

2024-12-28 05:36 UTC, patchang86 commented on lib/bcdice/game_system/DoubleCross.rb
>          if command == 'ET'
if command == 'PCP'
          return roll_prologue_chart_positive()
        end

        if command == 'PCN'
          return roll_prologue_chart_negative()
        end

2024-12-28 05:45 UTC, patchang86 commented on lib/bcdice/game_system/DoubleCross.rb
> +
```markdown
```suggestion

      # RW Prologue Chartを振る
       # @return [Result]
      def roll_prologue_chart_positive
        result = self.class::PROLOGUE_CHART_POSITIVE.roll(@randomizer)
        name = translate("DoubleCross.PCP.name")
        output_parts = ["#{name}(#{result.sum})", result.content]
        return Result.new(output_parts.join(' ＞ '))
      end
      # RW Prologue Chartを振る 2
       # @return [Result]
      def roll_prologue_chart_negative
        result = self.class::PROLOGUE_CHART_NEGATIVE.roll(@randomizer)
        name = translate("DoubleCross.PCN.name")
        output_parts = ["#{name}(#{result.sum})", result.content]
        return Result.new(output_parts.join(' ＞ '))
      end

2024-12-28 06:06 UTC, patchang86 commented on i18n/DoubleCross/ja_jp.yml
> +        "96_100": 順当な進行。このラウンド中に進行判定に成功したキャラクターは、進行値を+1得る。
```suggestion
"96_100": 順当な進行。このラウンド中に進行判定に成功したキャラクターは、進行値を+1得る。

    PCP:
      name: プロローグチャート(ポジティブ)
      items:
        "1" : 【ヴィクトリー】 ヴィランの集団と戦い、勝利する。報道陣や観衆がその勝利を称える。
        "2" : 【ハプニング】 銀行や商店などにいる際、突発的な犯罪に巻き込まれ、それを解決する。
        "3" : 【レスキュー】 火事や爆発事故、倒壊などの災害現場で、市民を救出する。
        "4" : 【ヴァーサス】 ライバルである強力なヴィランと対決している。決着はつかず、ヴィランは逃亡する。
        "5" : 【ヒーローインタビュー】 メディアから取材を受ける。事件の解決や首長からの表彰によって、あるいは注目のヒーローとしてなど。
        "6" : 【トレーニング】 ヒーローとしてトレーニングを行なっている。身体能力やエフェクトの訓練、知識の補強など。
        "7" : 【オリジン】 自分がヒーローとなったきっかけ、発端の場面を回想する。初めてオーヴァードに覚醒した場面や、初めて他人を救った時、かつての憧れのヒーローについてなど。
        "8" : 【エブリデイ・ライフ】 日常生活を送っている。久々の休暇か、ヒーロー以外の生活か。ロイスの対象と会話するのもよいだろう。
        "9" : 【ニューパワー】 新しいエフェクトや装備を身につける、受け取る。これで新たな力を手に入れたことになる。
        "10" : 【サクセス】 なにかに大成功した場面だ。仕事でもよいし、休暇中のゲームやスポーツかもしれない。 

    PCN:
      name: プロローグチャート(ネガティブ)
      items:
        "1" : 【ディフィート】 ヴィランと戦い、敗北した場面を回想する。その時の負傷は既に回復しているが、誇りはまだ回復していない。
        "2" : 【アクシデント】 不運に見舞われる。事故に巻き込まれる、たまたまヴィランの攻撃を受けるなど。その不幸で誰かが助かるかもしれない。
        "3" : 【ディザスター】 事故や災害に巻き込まれる、あるいは過去に巻き込まれた場面の回想。自分はオーヴァードの能力で生き残るが、他は⋯⋯。
        "4" : 【ウィークポイント】 ライバルである強力なヴィランと対決している。ヴィランはあなたの弱点や致命的欠陥、不吉な未来を告げて去っていく。
        "5" : 【バッシング】 メディアや市民から批判を受ける。過去の失敗や、今の乱暴な解決法など。
        "6" : 【リカバリー】 治療を受けている。最近怪我をした、過去の古傷が残っている、もう肉体が限界だ⋯⋯など。
        "7" : 【トラウマ】 過去の不幸、悲劇、失敗などを回想している。それがヒーローになったきっかけかもしれない。
        "8" : 【アキューズ】 あなたを責める会話。ロイスの対象、被害者の肉親など。それでもヒーローを続けるしかない⋯⋯。
        "9" : 【タイムリミット】 診療を受け、限界が近いことを告げられる。オーヴァードの能力に肉体が耐えられない、能力が衰えているなど。
        "10" : 【プリーズ】 ロイスの対象などから、ヒーローを引退するようにお願いされる。あなたが心配だ、危険すぎる、など。聞き入れるわけにはいかないが⋯⋯。

2024-12-28 06:08 UTC, patchang86 commented on lib/bcdice/game_system/DoubleCross.rb
if command == 'PCP'
          return roll_prologue_chart_positive()
        end
        if command == 'PCN'
          return roll_prologue_chart_negative()
        end

2024-12-28 06:16 UTC, patchang86 commented on lib/bcdice/game_system/DoubleCross.rb
>        end
```suggestion
        def prologue_chart_positive(locale)
           #DiceTable::RangeTable.new(
            I18n.translate("DoubleCross.PCP.name", locale: locale),
            "1D10",
            [
              # [0, '  '],
              [1,    I18n.translate("DoubleCross.PCP.items.1", locale: locale)],
              [2,   I18n.translate("DoubleCross.PCP.items.2", locale: locale)],
              [3,  I18n.translate("DoubleCross.PCP.items.3", locale: locale)],
              [4,  I18n.translate("DoubleCross.PCP.items.4", locale: locale)],
              [5,  I18n.translate("DoubleCross.PCP.items.5", locale: locale)],
              [6,  I18n.translate("DoubleCross.PCP.items.6", locale: locale)],
              [7,  I18n.translate("DoubleCross.PCP.items.7", locale: locale)],
              [8,  I18n.translate("DoubleCross.PCP.items.8", locale: locale)],
              [9,  I18n.translate("DoubleCross.PCP.items.9", locale: locale)],
              [10,  I18n.translate("DoubleCross.PCP.items.10", locale: locale)],
            ]
          )
        end

        def prologue_chart_negative(locale)
           #DiceTable::RangeTable.new(
            I18n.translate("DoubleCross.PCN.name", locale: locale),
            "1D10",
            [
              # [0, '  '],
              [1,    I18n.translate("DoubleCross.PCN.items.1", locale: locale)],
              [2,   I18n.translate("DoubleCross.PCN.items.2", locale: locale)],
              [3,  I18n.translate("DoubleCross.PCN.items.3", locale: locale)],
              [4,  I18n.translate("DoubleCross.PCN.items.4", locale: locale)],
              [5,  I18n.translate("DoubleCross.PCN.items.5", locale: locale)],
              [6,  I18n.translate("DoubleCross.PCN.items.6", locale: locale)],
              [7,  I18n.translate("DoubleCross.PCN.items.7", locale: locale)],
              [8,  I18n.translate("DoubleCross.PCN.items.8", locale: locale)],
              [9,  I18n.translate("DoubleCross.PCN.items.9", locale: locale)],
              [10,  I18n.translate("DoubleCross.PCN.items.10", locale: locale)],
            ]
          )
        end

2024-12-28 06:19 UTC, patchang86 commented on lib/bcdice/game_system/DoubleCross.rb
> +
# Prologue chart 
      PROLOGUE_CHART_POSITIVE = prologue_chart_positive(:ja_jp).freeze
      PROLOGUE_CHART_NEGATIVE = prologue_chart_negative(:ja_jp).freeze

2024-12-28 06:21 UTC, patchang86 commented on i18n/DoubleCross/ja_jp.yml
ついでにRWチャートも一気に入れてしまったらどうでしょうか？

2024-12-28 06:22 UTC, patchang86 requested changes
ついでにRWチャートも一気に入れてしまったらどうでしょうか？

2024-12-28 23:14 UTC, RYOSKATE commented
@patchang86 ありがとうございます。実装もほとんどいただいていたため、suggestion commitし、少し修正とテストまで追加いたしました。改めてご確認よろしくお願いいたします。

2024-12-29 10:22 UTC, patchang86 commented
あ！迷惑じゃなかったら幸いです。 Githubが苦手でインデントとかで大変お手数をおかけしました。 テストまでありがとうございました！ これで次のバージョンで一緒にアップデートされるといいですね~

2024-12-29 10:51 UTC, patchang86 approved these changes

2025-01-29 15:05 UTC, ysakasin requested changes
寄稿ありがとうございます。

今回追加されるいずれの表もクラスに内蔵された処理以上の特別な処理は指定はしていようなので、 以下を参考に `roll_tables` を使った方式に変更してください。

## サンプル
https://github.com/bcdice/BCDice/blob/556e4b1e169b5f27fb64936ddfdc8425a57340a8/example/OnseTool.rb#L24-L43

2025-01-29 23:28 UTC, RYOSKATE commented
@ysakasin ありがとうございます。提案いただいたroll_tablesを使った方式に変更してみるようにいたしました。改めてご確認よろしくお願いいたします。

2025-05-23 12:36 UTC, RYOSKATE commented
@ysakasin 恐れ入ります、先ほど https://github.com/bcdice/BCDice/pull/776 をマージされたと思います。
そちらのPRの内容は私の本PRの機能追加の韓国語翻訳が目的のようですが、私の本PR実装のコミットをマージやチェリーピックしているわけでもなくコピー＆ペーストをして取り込んでいらっしゃいます、これは実態として著作権的にも無断の複製と受け止められることと、私の機能実装の貢献が本リポジトリのGitのHistoryにも残らないことにつながると思い、大変残念に感じてしまいます。
先にこちらをマージしていただき、https://github.com/bcdice/BCDice/pull/776 の方に私の実装部分で競合発生しそちら解消後にマージという流れを想定していたため静観しておりましたが、先にあちらがマージされ、こちらが放置されている状況は意見させていただきたくメンションさせていただいております。
一度あちらリバートいただき、こちらをマージいただくことを強く希望いたします。何卒よろしくお願いいたします。

2025-05-23 13:24 UTC, merged

2025-05-23 13:31 UTC, RYOSKATE commented
@ysakasin 迅速にご対応いただけましてありがとうございます！