『キミトエール！』の追加
bcdice/BCDice pull request #741
Opened 2024-09-21 03:01 UTC by kurenai716

## 『守りたい人のために魔法を紡ぐTRPG　キミトエール！』のダイスボットを作成しました。
rubocop追加済みです。git、githubともに初めてなので不備がありましたらご指摘お願いします。
書籍情報：https://bouken.jp/prod/ttrpg/754

## 〇実装内容
### ・判定
`nKY6` or `nKY10` の形式で実装しました。
要求された判定とキャラクターのステータスによって判定ダイスの個数が変動し、かつ使用するダイスが6面もしくは10面ダイスとなるためnに入る数値でダイスの個数を、末尾の数値で使用するダイスを指定する形で実装しています。目標値は一律で4以上となるため、目標値の入力は省略しています。

4以上の出目が1つでもあれば判定は成功となり、1の目が出るとファンブル、6もしくは10（10面ダイスの場合はどちらが出てもよい）でスペシャルとなります。ファンブル時もほかに4以上の目があれば判定は成功となり、スペシャルとファンブルの両方が出た場合は共存しそれぞれを処理します。

### ・ランダム表
ファンブル表1つ、新しい出会い関連の表6つ、ランダム命名表8つを実装しました。新しい出会いとランダム命名表は一括振りのコマンドも実装しました。下記のとおりです。

        ─ ファンブル表（FT）
        ─ 新しい出会いを求める
          ─ 一括 新しい出会い表（NMTA） # New Meet Table
          ─ 新しい出会い表（NMT） # New Meet Table
          ─ 偶然出会った表（MCT） # Meet by Chance Table
          ─ 交流のなかった身近な人表（CIT） # someone Close to you but no Interaction Table
          ─ 助けてくれた人表（HYT） # someone Help You table
          ─ どんな人だったか表（TLT） # what's They Like Table
          ─ 変わった人だった表（EPT） # Eccentric Person Table
        ─ ランダム命名表
          ─ フルネーム一括生成（FNG） # Full Name Generation
          ─ 名字表（LNT） # LastName Table
          ─ 名前表（FNT） # FirstName Table
          ─ 日本名字表1（JLTO） # Japanese Lastname Table One
          ─ 日本名字表2（JLTT） # Japanese Lastname Table Two
          ─ カタカナ名字表（FLT） # Foreien Lastname Table
          ─ 日本名前表1（JFTO） # Japanese Firstname Table One
          ─ 日本名前表2（JFTT） # Japanese Firstname Table Two
          ─ カタカナ名前表（FFT） # Foreien Firstname Table

2025-01-27 10:54 UTC, ysakasin requested changes
長らくレビューを返さずにすみません。

すみませんが「ランダム命名表」は採用できないため、削除をお願いします。BCDiceではプレイ中に使うコマンドのみ実装しており、プリプレイやアフタープレイで主に使うコマンドは受け入れていません。

2025-01-27 11:24 UTC, kurenai716 commented
> 長らくレビューを返さずにすみません。
> 
> すみませんが「ランダム命名表」は採用できないため、削除をお願いします。BCDiceではプレイ中に使うコマンドのみ実装しており、プリプレイやアフタープレイで主に使うコマンドは受け入れていません。

レビューありがとうございます。

命名表については一度Discordの方で質問をして、導入してかまわないと返答いただいたという認識だったのですが、そういうわけではないのでしょうか？
以下のURLがDiscordでの投稿になります。
https://discord.com/channels/597133335243784192/598145833170501653/1283713003945984123

2025-01-27 14:16 UTC, ysakasin commented
すみません、Discordでのやり取りは忘れていました。今回は事前のチェックもしていたのでOKとします。

2025-01-27 22:32 UTC, kurenai716 commented
承知しました、お忙しい中ありがとうございます。

2025-01-28 13:37 UTC, ysakasin approved these changes

2025-01-28 13:38 UTC, merged