[Garactier]ガラクティア追加
bcdice/BCDice pull request #749
Opened 2024-12-18 08:59 UTC by JackyAniue

TRPGシステム『ガラクティア』のダイスボットを追加いたしました。
ルールブック（[https://booth.pm/ja/items/6164092）](https://booth.pm/ja/items/6164092%EF%BC%89)
ルールブック無料版（[https://booth.pm/ja/items/6164662）](https://booth.pm/ja/items/6164662%EF%BC%89)

[Kuuto7](https://github.com/Kuuto7)様の#745と拙作#746をマージしたものとなります。
よろしくお願いいたします。

ガラクティアVer1.03
x:基準値
y:目標値
x, yについては四則演算の入力が可能

■達成値の算出(GRx)
  クリティカル・ファンブルの判定、達成値の表示を行う。
■通常判定(GRx>=y)
  通常の判定を行う。
■命中判定(GRHx>=y)
  命中判定を行う。
■回避判定(GRDx>=y)
  回避判定を行う。
■抵抗判定(GRMx>=y)
  抵抗判定を行う。
■探索成功マスレベル算出(GRSx)
  探索・索敵判定時の最大成功マスレベル(ML)を算出する
■ 表
  アイテム決定表(ITMn)
    ランクnのアイテム表を振る。例)ITM2 ランク２アイテム表
    上級アイテムの判定も行います。
  命中部位決定表(BUI)
    命中時の部位を決定します。
  増強可能施設決定表(SST)
    報告フェイズの増強可能施設を決定します。

2024-12-29 15:52 UTC, JackyAniue commented
バージョン1.03から1.04にアイテム表を更新しました。

2025-01-29 09:31 UTC, JackyAniue commented
> `ArithmeticEvaluator.eval` は非推奨メソッドのため、 `Arithmetic.eval` を用いるように変更をお願いします。
修正いたしました。よろしくお願いいたします。

2025-01-29 15:29 UTC, ysakasin requested changes

2025-01-29 15:29 UTC, ysakasin commented on lib/bcdice/game_system/Garactier.rb
> +        end
Rubyではifも式で、戻り値を持つので以下のような書き方が適切かと思います。

```suggestion
        modifier = if m[1]
                     Arithmetic.eval(m[1], RoundType::FLOOR)
                   else
                     0
                   end
```
他の部分も同様に修正をお願いします。

2025-01-29 15:30 UTC, ysakasin commented on lib/bcdice/game_system/Garactier.rb
> +        end
もしくは、以下のようにしてしまうのも手です。

```ruby
modifier = Arithmetic.eval(m[1] || "", RoundType::FLOOR) || 0
```

2025-01-30 04:30 UTC, JackyAniue commented on lib/bcdice/game_system/Garactier.rb
> +        end
承知しました急ぎ修正いたします

2025-01-30 09:14 UTC, JackyAniue commented on lib/bcdice/game_system/Garactier.rb
> +        end
修正、マージいたしました。（2つ目の案をいただきました）
ありがとうございます！

2025-01-30 15:13 UTC, ysakasin requested changes

2025-01-30 15:13 UTC, ysakasin commented on lib/bcdice/game_system/Garactier.rb
> +            Integer success_level = (total - 4) / 2
```suggestion
            success_level = (total - 4) / 2
```

Rubyでは整数と整数の割り算は整数になるため、 `Integer` が切り捨ての処理を意図しているならば不要です。

2025-01-31 03:00 UTC, JackyAniue commented on lib/bcdice/game_system/Garactier.rb
> +            Integer success_level = (total - 4) / 2
削除、修正行いました。
Ruby不勉強で何度も申し訳ありません。

2025-05-23 13:55 UTC, merged